In [5]:
import pandas as pd
df1 = pd.read_csv("Bus_Stop_Shelter.csv")
df1.head()

,the_geom,BoroCode,BoroName,BoroCD,CounDist,AssemDist,StSenDist,CongDist,Shelter_ID,Corner,On_Street,Cross_Stre,Longitude,Latitude,NTAName,FEMAFldz,FEMAFldT,HrcEvac
0,POINT (-73.94874357365637 40.64085475597672),3,Brooklyn,317,45,42,21,9,BR02218,SW,AV D,NOSTRAND AV,-73.948745,40.640863,East Flatbush-Erasmus,X,AREA OF MINIMAL FLOOD HAZARD,5.0
1,POINT (-74.02283555116742 40.6292447605423),3,Brooklyn,310,43,46,26,11,BR02219,SW,5 AV,BAY RIDGE PKWY,-74.022837,40.629253,Bay Ridge,X,AREA OF MINIMAL FLOOD HAZARD,NaN
2,POINT (-73.92467258003798 40.67375874807616),3,Brooklyn,308,41,55,20,9,BR02220,SE,ST MARKS AV,BUFFALO AV,-73.924674,40.673767,Crown Heights (North),X,AREA OF MINIMAL FLOOD HAZARD,NaN
3,POINT (-73.9401345806071 40.578033768126936),3,Brooklyn,315,48,45,23,8,BR02221,SW,ORIENTAL BLVD,MACKENZIE ST,-73.940136,40.578042,Sheepshead Bay-Manhattan Beach-Gerritsen Beach,X,AREA OF MINIMAL FLOOD HAZARD,1.0
4,POINT (-73.93991658060635 40.57805676808165),3,Brooklyn,315,48,45,23,8,BR02222,SW,ORIENTAL BLVD,MACKENZIE ST,-73.939918,40.578065,Sheepshead Bay-Manhattan Beach-Gerritsen Beach,X,AREA OF MINIMAL FLOOD HAZARD,1.0

In [6]:
df2 = pd.read_csv("housing-new-york-units-by-building.csv")
df2.head()

,Project ID,Project Name,Program Group,Project Start Date,Project Completion Date,Building ID,Number,Street,Borough,Postcode,...,2-BR Units,3-BR Units,4-BR Units,5-BR Units,6-BR+ Units,Unknown-BR Units,Counted Rental Units,Counted Homeownership Units,All Counted Units,Total Units
0,68797,445 GERARD AVENUE,Multifamily Incentives Program,2020-12-31T00:00:00.000,NaN,991233.0,445,GERARD AVENUE,Bronx,10451.0,...,20,0,0,0,0,0,71,0,71,338
1,68866,MAXWELL DEVELOPMENT LP.YR15.FY21,Multifamily Finance Program,2020-12-31T00:00:00.000,NaN,41403.0,143,WEST 140 STREET,Manhattan,10030.0,...,27,7,7,0,0,0,55,0,55,55
2,68866,MAXWELL DEVELOPMENT LP.YR15.FY21,Multifamily Finance Program,2020-12-31T00:00:00.000,NaN,41405.0,151,WEST 140 STREET,Manhattan,10030.0,...,20,7,7,0,0,0,55,0,55,55
3,68866,MAXWELL DEVELOPMENT LP.YR15.FY21,Multifamily Finance Program,2020-12-31T00:00:00.000,NaN,41431.0,227,WEST 140 STREET,Manhattan,10030.0,...,13,4,0,0,0,0,20,0,20,20
4,68866,MAXWELL DEVELOPMENT LP.YR15.FY21,Multifamily Finance Program,2020-12-31T00:00:00.000,NaN,41436.0,233,WEST 140 STREET,Manhattan,10030.0,...,17,8,0,0,0,0,31,0,31,31

In [7]:
type(df1['the_geom'])

pandas.core.series.Series

In [8]:
print(df1['the_geom'][5:])

5       POINT (-73.95872756901241 40.68286474752799)
6        POINT (-73.96644956410857 40.7051227439722)
7       POINT (-73.94304857309739 40.68010074811949)
8       POINT (-73.92847258069996 40.63257075644031)
9       POINT (-73.92860558149378 40.63273675622538)
                            ...
3325     POINT (-74.11221352595592 40.5678197761412)
3326    POINT (-74.16856250790204 40.57400177692753)
3327    POINT (-74.09298952767594 40.64534875958313)
3328    POINT (-74.12038852436673 40.56029177738492)
3329     POINT (-74.11976852484383 40.5604317775396)
Name: the_geom, Length: 3325, dtype: object

In [19]:
import geopy.distance

In [65]:
df1['Longitude'].dropna().reset_index(drop=True)
df1['Latitude'].dropna().reset_index(drop=True)

0       40.640863
1       40.629253
2       40.673767
3       40.578042
4       40.578065
          ...
3325    40.567828
3326    40.574010
3327    40.645357
3328    40.560300
3329    40.560440
Name: Latitude, Length: 3330, dtype: float64

In [84]:
df2['Longitude'].dropna().reset_index(drop=True)
df2['Latitude'].dropna().reset_index(drop=True)

0       40.817398
1       40.817879
2       40.817947
3       40.818904
4       40.818953
          ...
3901    40.798269
3902    40.664986
3903    40.664945
3904    40.664166
3905    40.663863
Name: Latitude, Length: 3906, dtype: float64

In [74]:
def distance_2points(row):
    coord1 = (df1['Latitude'], df1['Longitude'])
    coord2 = (df2['Latitude'], df2['Longitude'])
    distance = geopy.distance.geodesic(coord1, coord2).km
    return distance

df1['distance'] = df1.apply(distance_2points, axis=1)

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [75]:
print(coordinate_distance())

ValueError: Point coordinates must be finite. (nan, nan, 0.0) has been passed as coordinates.

In [76]:
df1.isnull().values.any()

True

In [83]:
df1['Latitude'].isnull().sum().sum()

0

In [86]:
df2["Longitude"].isnull().sum().sum()

1053

In [87]:
df1_new = df1[df1['Longitude'].notna()]

In [89]:
len(df1)

3330

In [90]:
len(df1_new)

3330

In [91]:
len(df2)

4959

In [103]:
df2_new =df2[df2['Longitude'].notna()].reset_index(drop=True)

In [104]:
len(df2_new)

3906

In [105]:
df2_new = df2_new[df2_new['Latitude'].notna()].reset_index(drop=True)

In [106]:
len(df2_new)

3906

In [110]:
def coordinate_distance():
    lst = []
    for i in range(len(df1_new['Latitude'])):
        for j in range(len(df2_new['Latitude'])):
            coords_1 = (df1_new['Latitude'][i], df1_new['Longitude'][i])
            coords_2 = (df2_new['Latitude'][j], df2_new['Longitude'][j])
            if geopy.distance.geodesic(coords_1, coords_2).km <= 0.5:
                lst.append(geopy.distance.geodesic(coords_1, coords_2).km)
    return lst

In [112]:
print(coordinate_distance())

KeyboardInterrupt:

In [101]:
df1_new[42:]

,the_geom,BoroCode,BoroName,BoroCD,CounDist,AssemDist,StSenDist,CongDist,Shelter_ID,Corner,On_Street,Cross_Stre,Longitude,Latitude,NTAName,FEMAFldz,FEMAFldT,HrcEvac
42,POINT (-73.95978257418842 40.5818057677528),3,Brooklyn,313,48,45,23,8,BR02016,SE,CONEY ISLAND AV,NEPTUNE AV,-73.959784,40.581814,Brighton Beach,AE,NaN,1.0
43,POINT (-73.96079857367232 40.591297765607415),3,Brooklyn,315,48,45,22,8,BR02019,SW,CONEY ISLAND AV,AV X,-73.960800,40.591306,Gravesend (South),X,AREA OF MINIMAL FLOOD HAZARD,3.0
44,POINT (-73.94077857921191 40.59393876488273),3,Brooklyn,315,48,41,22,8,BR02020,NW,NOSTRAND AV,AV X,-73.940780,40.593947,Sheepshead Bay-Manhattan Beach-Gerritsen Beach,X,AREA OF MINIMAL FLOOD HAZARD,3.0
45,POINT (-73.96738157074715 40.6054087632593),3,Brooklyn,315,44,45,22,9,BR02021,SW,KINGS HWY,OCEAN PKWY,-73.967383,40.605417,Gravesend (East)-Homecrest,X,AREA OF MINIMAL FLOOD HAZARD,5.0
46,POINT (-73.93753058050379 40.600972763400875),3,Brooklyn,315,46,41,22,8,BR02022,NW,AV U,COYLE ST,-73.937532,40.600981,Madison,X,AREA OF MINIMAL FLOOD HAZARD,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3325,POINT (-74.11221352595592 40.5678197761412),5,Staten Island,502,50,64,24,11,SI05219,NE,Hylan Blvd,Beach Av,-74.112215,40.567828,New Dorp-Midland Beach,X,AREA OF MINIMAL FLOOD HAZARD,4.0
3326,POINT (-74.16856250790204 40.57400177692753),5,Staten Island,502,51,63,24,11,SI05220,NW,Independence Av,Pathmark,-74.168564,40.574010,New Springville-Willowbrook-Bulls Head-Travis,X,AREA OF MINIMAL FLOOD HAZARD,3.0
3327,POINT (-74.09298952767594 40.64534875958313),5,Staten Island,501,49,61,23,11,SI05221,SW,Richmond Terrace,Franklin Av,-74.092991,40.645357,St. George-New Brighton,X,AREA OF MINIMAL FLOOD HAZARD,NaN
3328,POINT (-74.12038852436673 40.56029177738492),5,Staten Island,503,50,64,24,11,SI05222,SW,HYLAN BLVD,GUYON AV,-74.120390,40.560300,Oakwood-Richmondtown,X,0.2 PCT ANNUAL CHANCE FLOOD HAZARD,2.0
3329,POINT (-74.11976852484383 40.5604317775396),5,Staten Island,503,50,64,24,11,SI05223,NE,HYLAN BLVD,GUYON AV,-74.119770,40.560440,Oakwood-Richmondtown,X,0.2 PCT ANNUAL CHANCE FLOOD HAZARD,2.0

In [107]:
df2_new[40:]

,Project ID,Project Name,Program Group,Project Start Date,Project Completion Date,Building ID,Number,Street,Borough,Postcode,...,2-BR Units,3-BR Units,4-BR Units,5-BR Units,6-BR+ Units,Unknown-BR Units,Counted Rental Units,Counted Homeownership Units,All Counted Units,Total Units
40,66722,CALVARY BAPTIST. HUDMF. FY20,Multifamily Finance Program,2020-12-17T00:00:00.000,NaN,643979.0,160-30,CLAUDE AVENUE,Queens,11433.0,...,1,0,0,0,0,0,100,0,100,100
41,66879,COMPASS 6,Multifamily Finance Program,2020-12-17T00:00:00.000,NaN,989183.0,1923,WEST FARMS ROAD,Bronx,10460.0,...,56,27,0,0,0,0,261,0,261,261
42,68125,CUCS. 711 EAST 211TH ST AND 718 EAST 212TH ST.,Multifamily Finance Program,2020-12-17T00:00:00.000,NaN,996758.0,718,EAST 212 STREET,Bronx,10467.0,...,22,27,0,0,0,0,87,0,87,87
43,68125,CUCS. 711 EAST 211TH ST AND 718 EAST 212TH ST.,Multifamily Finance Program,2020-12-17T00:00:00.000,NaN,996771.0,713,EAST 211 STREET,Bronx,10467.0,...,36,0,0,0,0,0,83,0,83,83
44,68132,DOUGLASTON. 2856 WEBSTER AVENUE,Multifamily Finance Program,2020-12-17T00:00:00.000,NaN,996730.0,2856,WEBSTER AVENUE,Bronx,10458.0,...,1,0,0,0,0,0,188,0,188,188
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3901,50682,74 W 105th Street,Multifamily Incentives Program,2014-01-21T00:00:00.000,2014-01-21T00:00:00.000,37582.0,74,WEST 105 STREET,Manhattan,10025.0,...,1,0,0,0,0,0,10,0,10,10
3902,49722,Livonia Commons,Multifamily Finance Program,2014-01-15T00:00:00.000,2016-04-25T00:00:00.000,948722.0,491,SHEFFIELD AVENUE,Brooklyn,11207.0,...,17,6,0,0,0,0,52,0,52,52
3903,49722,Livonia Commons,Multifamily Finance Program,2014-01-15T00:00:00.000,2016-04-25T00:00:00.000,948723.0,494,SHEFFIELD AVE,Brooklyn,11207.0,...,41,5,0,0,0,0,84,0,84,84
3904,49722,Livonia Commons,Multifamily Finance Program,2014-01-15T00:00:00.000,2016-04-25T00:00:00.000,948724.0,494,GEORGIA AVENUE,Brooklyn,11207.0,...,20,5,0,0,0,0,90,0,90,90
3905,49722,Livonia Commons,Multifamily Finance Program,2014-01-15T00:00:00.000,2016-04-25T00:00:00.000,969838.0,481,WILLIAMS AVENUE,Brooklyn,11207.0,...,17,6,0,0,0,0,52,0,52,52

In [113]:
def coordinate_distance():
    coords_1 = [(lat, lon) for lat, lon in zip(df1_new['Latitude'], df1_new['Longitude'])]
    coords_2 = [(lat, lon) for lat, lon in zip(df2_new['Latitude'], df2_new['Longitude'])]
    distances = [geopy.distance.geodesic(c1, c2).km for c1 in coords_1 for c2 in coords_2 if geopy.distance.geodesic(c1, c2).km <= 0.5]
    return distances

In [115]:
from scipy.spatial import cKDTree
import numpy as np

def coordinate_distance_optimized():
    lst = []
    coords_1 = np.array(df1_new[['Latitude', 'Longitude']])
    coords_2 = np.array(df2_new[['Latitude', 'Longitude']])
    
    # Build KD-trees for the two sets of coordinates
    tree_1 = cKDTree(coords_1)
    tree_2 = cKDTree(coords_2)
    
    # Find pairs of coordinates that are within 0.5 km of each other
    pairs = tree_1.query_ball_tree(tree_2, r=0.5, p=2.0)
    
    # Iterate over the pairs and calculate their distances
    for i, pair in enumerate(pairs):
        for j in pair:
            dist = geopy.distance.geodesic(coords_1[i], coords_2[j]).km
            lst.append(dist)
    
    return lst

In [122]:
def coordinate_distance():
    coords_1 = [(lat, lon) for lat, lon in zip(df1_new['Latitude'], df1_new['Longitude'])]
    coords_2 = [(lat, lon) for lat, lon in zip(df2_new['Latitude'], df2_new['Longitude'])]
    distances = [[geopy.distance.geodesic(c1, c2).km for c2 in coords_2 if geopy.distance.geodesic(c1, c2).km <= 0.5] for c1 in coords_1]
    return distances

In [149]:
df3 = pd.read_csv("scores.csv")
df3.head()

,School ID,School Name,Borough,Building Code,Street Address,City,State,Zip Code,Latitude,Longitude,...,End Time,Student Enrollment,Percent White,Percent Black,Percent Hispanic,Percent Asian,Average Score (SAT Math),Average Score (SAT Reading),Average Score (SAT Writing),Percent Tested
0,02M260,Clinton School Writers and Artists,Manhattan,M933,425 West 33rd Street,Manhattan,NY,10001,40.75321,-73.99786,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,06M211,Inwood Early College for Health and Informatio...,Manhattan,M052,650 Academy Street,Manhattan,NY,10002,40.86605,-73.92486,...,3:00 PM,87.0,3.4%,21.8%,67.8%,4.6%,NaN,NaN,NaN,NaN
2,01M539,"New Explorations into Science, Technology and ...",Manhattan,M022,111 Columbia Street,Manhattan,NY,10002,40.71873,-73.97943,...,4:00 PM,1735.0,28.6%,13.3%,18.0%,38.5%,657.0,601.0,601.0,91.0%
3,02M294,Essex Street Academy,Manhattan,M445,350 Grand Street,Manhattan,NY,10002,40.71687,-73.98953,...,2:45 PM,358.0,11.7%,38.5%,41.3%,5.9%,395.0,411.0,387.0,78.9%
4,02M308,Lower Manhattan Arts Academy,Manhattan,M445,350 Grand Street,Manhattan,NY,10002,40.71687,-73.98953,...,3:00 PM,383.0,3.1%,28.2%,56.9%,8.6%,418.0,428.0,415.0,65.1%

In [150]:
df3_new =df3[df3['Longitude'].notna()].reset_index(drop=True)

In [151]:
len(df3)

435

In [152]:
len(df3_new)

435

In [153]:
df3_new =df3_new[df3_new['Latitude'].notna()].reset_index(drop=True)

In [154]:
len(df3_new)

435

In [155]:
def coordinate_distance():
    coords_1 = [(lat, lon) for lat, lon in zip(df1_new['Latitude'], df1_new['Longitude'])]
    coords_2 = [(lat, lon) for lat, lon in zip(df2_new['Latitude'], df2_new['Longitude'])]
    distances = {}
    for c1 in coords_1:
        distances[c1] = [[c2, geopy.distance.geodesic(c1, c2).km] for c2 in coords_2 if geopy.distance.geodesic(c1, c2).km <= 0.5]
    return distances

In [182]:
df1_new_s = df1_new.sample(n=500,axis='rows',replace=True).reset_index(drop=True)

In [183]:
len(df1_new_s)

500

In [184]:
df1_new_s[df1_new_s['BoroName'] == "Manhattan"]

,the_geom,BoroCode,BoroName,BoroCD,CounDist,AssemDist,StSenDist,CongDist,Shelter_ID,Corner,On_Street,Cross_Stre,Longitude,Latitude,NTAName,FEMAFldz,FEMAFldT,HrcEvac
15,POINT (-73.96877855821629 40.791336726945026),1,Manhattan,107,6,69,47,12,MN01123,SW,COLUMBUS AV,W 94 ST,-73.968780,40.791345,Upper West Side (Central),X,AREA OF MINIMAL FLOOD HAZARD,NaN
16,POINT (-73.94620156389976 40.83258071848255),1,Manhattan,109,7,71,30,13,MN0334,SW,BROADWAY,W 155 ST,-73.946203,40.832589,Hamilton Heights-Sugar Hill,X,AREA OF MINIMAL FLOOD HAZARD,NaN
36,POINT (-74.00745055053041 40.727992740429244),1,Manhattan,102,3,66,27,10,MN01374,SW,KING ST,HUDSON ST,-74.007452,40.728001,SoHo-Little Italy-Hudson Square,X,AREA OF MINIMAL FLOOD HAZARD,2.0
55,POINT (-74.012578549153 40.7081757443707),1,Manhattan,101,1,61,27,10,MN01276,NE,TRINITY PL,RECTOR ST,-74.012580,40.708184,Financial District-Battery Park City,X,AREA OF MINIMAL FLOOD HAZARD,5.0
60,POINT (-73.93709956787848 40.81040172176217),1,Manhattan,111,9,70,30,13,MN0863,NE,MADISON AV,E 132 ST,-73.937101,40.810410,East Harlem (North),X,AREA OF MINIMAL FLOOD HAZARD,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
489,POINT (-73.9836905551145 40.775580730957444),1,Manhattan,107,6,67,47,12,MN01264,NE,AMSTERDAM AV,W 67 ST,-73.983692,40.775589,Upper West Side-Lincoln Square,X,AREA OF MINIMAL FLOOD HAZARD,NaN
491,POINT (-73.9425285666306 40.806185722915764),1,Manhattan,110,9,70,30,13,MN9029,SW,5 AV,W 125 ST,-73.942530,40.806194,Harlem (South),X,AREA OF MINIMAL FLOOD HAZARD,6.0
494,POINT (-73.98756255578506 40.73300173918005),1,Manhattan,103,2,66,27,10,MN0140,SW,3 AV,E 14 ST,-73.987564,40.733010,East Village,X,AREA OF MINIMAL FLOOD HAZARD,NaN
495,POINT (-73.93690856775602 40.80404172346843),1,Manhattan,111,8,68,30,13,MN01646,SE,E 125 ST,LEXINGTON AV,-73.936910,40.804050,East Harlem (North),X,AREA OF MINIMAL FLOOD HAZARD,5.0
498,POINT (-73.97201455989763 40.76202673257308),1,Manhattan,105,4,73,28,12,MN01467,SE,E 57 ST,MADISON AV,-73.972016,40.762035,Midtown-Times Square,X,AREA OF MINIMAL FLOOD HAZARD,NaN

In [185]:
df2_new_s = df2_new.sample(n=500,axis='rows',replace=True).reset_index(drop=True)

In [186]:
df2_new_s

,Project ID,Project Name,Program Group,Project Start Date,Project Completion Date,Building ID,Number,Street,Borough,Postcode,...,2-BR Units,3-BR Units,4-BR Units,5-BR Units,6-BR+ Units,Unknown-BR Units,Counted Rental Units,Counted Homeownership Units,All Counted Units,Total Units
0,69484,HP WEST 49TH STREET PORTFOLIO HDFC.HPO.FY21,Multifamily Finance Program,2020-11-27T00:00:00.000,NaN,33728.0,328,WEST 49 STREET,Manhattan,10019.0,...,9,0,0,0,0,0,12,0,12,20
1,67231,WEST END. 483 WEST END AVE. WEST END INTERGENE...,Multifamily Finance Program,2018-06-22T00:00:00.000,2018-06-22T00:00:00.000,44024.0,483,WEST END AVENUE,Manhattan,10024.0,...,0,0,0,0,0,0,40,0,40,40
2,53254,Christopher Court,Multifamily Incentives Program,2014-06-11T00:00:00.000,2014-06-11T00:00:00.000,806839.0,599,MORRIS AVENUE,Bronx,10451.0,...,86,42,0,0,0,0,160,0,160,160
3,69740,516 WEST 162 STREET APARTMENTS,Multifamily Incentives Program,2020-02-10T00:00:00.000,2020-02-10T00:00:00.000,966857.0,516,WEST 162 STREET,Manhattan,10032.0,...,1,0,0,0,0,0,4,0,4,20
4,57668,WSFSSH. 275 EAST138TH ST. TRES PUENTES,Multifamily Finance Program,2016-05-19T00:00:00.000,2018-12-31T00:00:00.000,966537.0,271,EAST 138 STREET,Bronx,10454.0,...,0,0,0,0,0,0,119,0,119,119
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,53655,DREAMYARD NEP HDFC.YR15.FY2017,Multifamily Finance Program,2017-06-27T00:00:00.000,NaN,56805.0,1107,CLAY AVENUE,Bronx,10456.0,...,35,11,0,0,0,0,55,0,55,55
496,59857,Stuy Town Peter Cooper Village,Multifamily Finance Program,2015-12-18T00:00:00.000,2015-12-18T00:00:00.000,804067.0,271,AVENUE C,Manhattan,10009.0,...,18,2,0,0,0,0,43,0,43,43
497,66586,STRYCKER'S BAY,Multifamily Finance Program,2017-10-30T00:00:00.000,2020-02-03T00:00:00.000,806136.0,66,WEST 94 STREET,Manhattan,10025.0,...,58,19,19,0,0,0,0,114,114,114
498,53157,MHANY 75,Multifamily Finance Program,2015-10-27T00:00:00.000,2018-08-03T00:00:00.000,376867.0,721,STERLING PLACE,Brooklyn,11216.0,...,0,0,4,0,0,0,4,0,4,4
499,68585,WEST 135TH STREET APARTMENTS,Multifamily Finance Program,2019-05-19T00:00:00.000,NaN,40710.0,143,WEST 135 STREET,Manhattan,10030.0,...,10,6,0,0,0,0,18,0,18,18

In [187]:
df3_new_s = df3_new.sample(n=50,axis='rows',replace=True).reset_index(drop=True)

In [188]:
df3_new_s

,School ID,School Name,Borough,Building Code,Street Address,City,State,Zip Code,Latitude,Longitude,...,End Time,Student Enrollment,Percent White,Percent Black,Percent Hispanic,Percent Asian,Average Score (SAT Math),Average Score (SAT Reading),Average Score (SAT Writing),Percent Tested
0,05M362,Columbia Secondary School,Manhattan,M125,425 West 123rd Street,Manhattan,NY,10027,40.81092,-73.95693,...,4:00 PM,659.0,14.8%,22.0%,48.1%,13.7%,583.0,561.0,546.0,88.2%
1,12X479,Bronx Career and College Preparatory High School,Bronx,X158,800 Home Street,Bronx,NY,10456,40.82776,-73.90039,...,2:15 PM,333.0,0.6%,40.5%,56.8%,0.9%,370.0,379.0,381.0,40.7%
2,24Q236,International High School for Health Sciences,Queens,Q455,48-01 90th Street,Elmhurst,NY,11373,40.74121,-73.87473,...,3:30 PM,159.0,8.8%,5.7%,63.5%,21.4%,NaN,NaN,NaN,NaN
3,12X550,High School of World Cultures,Bronx,X420,1300 Boynton Avenue,Bronx,NY,10472,40.83137,-73.87882,...,4:00 PM,410.0,1.2%,8.3%,80.2%,8.0%,356.0,359.0,347.0,38.2%
4,31R600,Ralph R. McKee Career and Technical Education ...,Staten Island,R600,290 St Marks Place,Staten Island,NY,10301,40.64274,-74.07871,...,3:00 PM,624.0,19.7%,30.8%,42.5%,4.8%,420.0,429.0,409.0,38.0%
5,09X413,Bronx High School for Medical Science,Bronx,X410,240 East 172nd Street,Bronx,NY,10457,40.84037,-73.91084,...,3:15 PM,472.0,0.7%,36.7%,53.4%,7.1%,431.0,421.0,426.0,83.9%
6,02M416,Eleanor Roosevelt High School,Manhattan,M855,411 East 76th Street,Manhattan,NY,10021,40.77012,-73.95338,...,3:30 PM,541.0,61.4%,4.4%,10.9%,20.1%,641.0,617.0,631.0,86.0%
7,30Q555,Newcomers High School,Queens,Q450,28-01 41st Avenue,Long Island City,NY,11101,40.75138,-73.93745,...,3:00 PM,993.0,6.2%,2.4%,54.6%,36.7%,490.0,374.0,381.0,47.1%
8,08X558,Westchester Square Academy,Bronx,X405,3000 East Tremont Avenue,Bronx,NY,10461,40.84051,-73.83812,...,3:20 PM,396.0,8.8%,26.8%,56.6%,4.5%,NaN,NaN,NaN,NaN
9,07X259,"HERO High (Health, Education, and Research Occ...",Bronx,X655,455 Southern Boulevard,Bronx,NY,10455,40.81041,-73.90680,...,3:30 PM,231.0,1.7%,35.5%,58.9%,2.2%,NaN,NaN,NaN,NaN
10,19K764,Urban Assembly School for Collaborative Health...,Brooklyn,K420,999 Jamaica Avenue,Brooklyn,NY,11208,40.69114,-73.86843,...,3:15 PM,62.0,4.8%,40.3%,32.3%,11.3%,NaN,NaN,NaN,NaN
11,06M468,High School for Health Careers and Sciences,Manhattan,M465,549 Audubon Avenue,Manhattan,NY,10040,40.85594,-73.92703,...,3:45 PM,605.0,1.5%,15.9%,79.8%,1.3%,374.0,385.0,389.0,56.2%
12,02M439,Manhattan Village Academy,Manhattan,M873,43 West 22nd Street,Manhattan,NY,10010,40.74149,-73.99145,...,3:20 PM,415.0,7.2%,9.6%,67.2%,7.2%,522.0,479.0,510.0,98.8%
13,11X290,Bronx Academy of Health Careers,Bronx,X425,800 East Gun Hill Road,Bronx,NY,10467,40.87575,-73.86139,...,3:15 PM,465.0,1.9%,44.7%,47.3%,4.7%,386.0,380.0,391.0,59.4%
14,29Q272,George Washington Carver High School for the S...,Queens,Q420,143-10 Springfield Boulevard,Springfield Gardens,NY,11413,40.66823,-73.75684,...,3:15 PM,509.0,1.8%,75.6%,11.4%,9.4%,439.0,428.0,419.0,63.5%
15,13K350,Urban Assembly High School of Music and Art,Brooklyn,K805,49 Flatbush Avenue Extension,Brooklyn,NY,11201,40.69717,-73.98496,...,4:00 PM,387.0,0.5%,77.5%,20.7%,0.5%,372.0,372.0,361.0,55.1%
16,02M600,High School of Fashion Industries,Manhattan,M600,225 West 24th Street,Manhattan,NY,10011,40.74511,-73.99591,...,3:45 PM,1770.0,3.8%,36.3%,53.8%,5.0%,433.0,442.0,427.0,80.6%
17,31R080,Michael J. Petrides School,Staten Island,R880,715 Ocean Terrace,Staten Island,NY,10301,40.60745,-74.10148,...,2:20 PM,1327.0,49.8%,22.3%,20.2%,6.9%,483.0,473.0,470.0,79.2%
18,27Q323,Scholars' Academy,Queens,Q180,320 Beach 104th Street,Rockaway Park,NY,11694,40.58413,-73.82568,...,3:00 PM,1302.0,34.7%,22.7%,19.6%,21.4%,588.0,560.0,568.0,99.2%
19,24Q550,High School for Arts and Business,Queens,Q456,105-25 Horace Harding Expressway,Corona,NY,11368,40.73742,-73.85331,...,4:00 PM,870.0,4.1%,7.8%,77.2%,10.2%,413.0,405.0,393.0,76.7%
20,02M425,Leadership and Public Service High School,Manhattan,M894,90 Trinity Place,Manhattan,NY,10006,40.70915,-74.01208,...,2:45 PM,699.0,4.4%,27.9%,61.9%,3.9%,390.0,396.0,392.0,54.9%
21,12X684,Wings Academy,Bronx,X879,1122 East 180th Street,Bronx,NY,10460,40.84181,-73.87542,...,3:00 PM,501.0,1.2%,58.5%,37.9%,0.8%,379.0,372.0,373.0,49.2%
22,13K430,Brooklyn Technical High School,Brooklyn,K430,29 Ft Greene Place,Brooklyn,NY,11217,40.68811,-73.97675,...,3:15 PM,5447.0,20.5%,7.7%,7.6%,60.5%,682.0,608.0,606.0,95.5%
23,16K688,Brooklyn Academy of Global Finance,Brooklyn,K057,125 Stuyvesant Avenue,Brooklyn,NY,11221,40.69154,-73.93373,...,3:12 PM,152.0,2.0%,71.7%,20.4%,5.9%,395.0,382.0,391.0,45.9%
24,32K403,Academy for Environmental Leadership,Brooklyn,K480,400 Irving Avenue,Brooklyn,NY,11237,40.69696,-73.91082,...,3:00 PM,340.0,1.5%,19.4%,77.1%,1.8%,365.0,366.0,348.0,71.3%
25,32K552,Academy of Urban Planning,Brooklyn,K480,400 Irving Avenue,Brooklyn,NY,11237,40.69696,-73.91082,...,3:45 PM,279.0,0.7%,23.3%,73.8%,0.7%,392.0,374.0,379.0,41.9%
26,31R455,Tottenville High School,Staten Island,R455,100 Luten Avenue,Staten Island,NY,10312,40.52823,-74.19215,...,2:45 PM,3982.0,79.9%,1.8%,11.8%,5.1%,494.0,476.0,476.0,78.9%
27,09X227,Bronx Collegiate Academy,Bronx,X410,240 East 172nd Street,Bronx,NY,10457,40.84037,-73.91084,...,3:30 PM,382.0,0.3%,28.5%,69.1%,1.0%,395.0,401.0,382.0,45.5%
28,14K586,Lyons Community School,Brooklyn,K049,223 Graham Avenue,Brooklyn,NY,11206,40.70990,-73.94366,...,3:30 PM,520.0,2.4%,39.8%,55.8%,1.8%,374.0,376.0,357.0,56.3%
29,26Q495,Bayside High School,Queens,Q405,32-24 Corporal Kennedy Street,Bayside,NY,11361,40.77187,-73.78039,...,3:30 PM,3336.0,18.1%,13.0%,27.9%,40.3%,523.0,479.0,485.0,76.7%
30,12X682,Fannie Lou Hamer Freedom High School,Bronx,X878,1021 Jennings Street,Bronx,NY,10460,40.83081,-73.88602,...,2:45 PM,470.0,0.2%,28.5%,70.4%,0.4%,345.0,347.0,339.0,75.0%
31,04M495,Park East High School,Manhattan,M495,230 East 105th Street,Manhattan,NY,10029,40.79056,-73.94445,...,3:15 PM,413.0,1.7%,27.6%,63.7%,4.8%,429.0,433.0,435.0,89.6%
32,24Q299,Bard High School Early College Queens,Queens,Q735,30-20 Thomson Avenue,Long Island City,NY,11101,40.74509,-73.93681,...,3:20 PM,623.0,34.5%,11.4%,17.0%,34.2%,631.0,598.0,610.0,94.1%
33,10X225,Theatre Arts Production Company School,Bronx,X137,2225 Webster Avenue,Bronx,NY,10457,40.85465,-73.89665,...,3:30 PM,632.0,0.7%,29.2%,66.6%,1.2%,402.0,421.0,410.0,77.7%
34,01M696,Bard High School Early College,Manhattan,M097,525 East Houston Street,Manhattan,NY,10002,40.71896,-73.97607,...,3:50 PM,545.0,45.3%,17.2%,18.7%,17.1%,634.0,641.0,639.0,70.8%
35,07X427,Community School for Social Justice,Bronx,X884,350 Gerard Avenue,Bronx,NY,10451,40.81608,-73.93032,...,3:00 PM,324.0,1.2%,29.6%,67.3%,1.5%,380.0,382.0,362.0,38.4%
36,10X445,Bronx High School of Science,Bronx,X445,75 West 205th Street,Bronx,NY,10468,40.87706,-73.88978,...,3:45 PM,3015.0,22.1%,2.6%,5.5%,62.8%,714.0,660.0,667.0,97.0%
37,18K617,High School for Innovation in Advertising and ...,Brooklyn,K500,1600 Rockaway Parkway,Brooklyn,NY,11236,40.64184,-73.89869,...,3:15 PM,303.0,2.6%,85.8%,9.6%,1.3%,390.0,410.0,397.0,59.1%
38,12X388,Pan American International High School at Monroe,Bronx,X420,1300 Boynton Avenue,Bronx,NY,10472,40.83137,-73.87882,...,5:30 PM,428.0,0.0%,0.0%,100.0%,0.0%,317.0,315.0,292.0,65.6%
39,08X432,Bronx Bridges High School,Bronx,X450,1980 Lafayette Avenue,Bronx,NY,10473,40.82230,-73.85596,...,3:45 PM,333.0,1.8%,6.6%,82.9%,7.8%,NaN,NaN,NaN,1.2%
40,03M417,Frank McCourt High School,Manhattan,M470,145 West 84th Street,Manhattan,NY,10024,40.78574,-73.97442,...,3:00 PM,387.0,31.8%,15.8%,40.1%,8.8%,489.0,491.0,500.0,89.1%
41,27Q334,Epic High School North,Queens,Q636,94-25 117th Street,South Richmond Hill,NY,11419,40.69288,-73.82931,...,4:00 PM,93.0,5.4%,21.5%,37.6%,19.4%,NaN,NaN,NaN,NaN
42,09X350,New Directions Secondary School,Bronx,X410,240 East 172nd Street,Bronx,NY,10457,40.84037,-73.91084,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,15K448,Brooklyn Secondary School for Collaborative St...,Brooklyn,K142,610 Henry Street,Brooklyn,NY,11231,40.67986,-74.00148,...,2:50 PM,685.0,9.3%,38.5%,45.3%,5.8%,401.0,411.0,404.0,84.1%
44,14K610,Automotive High School,Brooklyn,K610,50 Bedford Avenue,Brooklyn,NY,11222,40.72264,-73.95258,...,3:50 PM,383.0,2.9%,55.9%,38.1%,1.6%,367.0,381.0,328.0,31.6%
45,05M367,Academy for Social Action (College Board),Manhattan,M043,509 West 129th Street,Manhattan,NY,10027,40.81523,-73.95520,...,3:45 PM,234.0,2.8%,46.5%,49.3%,0.5%,357.0,349.0,365.0,54.0%
46,02M437,Hudson High School of Learning Technologies,Manhattan,M440,351 West 18th Street,Manhattan,NY,10011,40.74289,-74.00213,...,3:30 PM,483.0,3.3%,29.2%,59.4%,6.4%,378.0,407.0,388.0,71.8%
47,02M437,Hudson High School of Learning Technologies,Manhattan,M440,351 West 18th Street,Manhattan,NY,10011,40.74289,-74.00213,...,3:30 PM,483.0,3.3%,29.2%,59.4%,6.4%,378.0,407.0,388.0,71.8%
48,12X479,Bronx Career and College Preparatory High School,Bronx,X158,800 Home Street,Bronx,NY,10456,40.82776,-73.90039,...,2:15 PM,333.0,0.6%,40.5%,56.8%,0.9%,370.0,379.0,381.0,40.7%
49,12X682,Fannie Lou Hamer Freedom High School,Bronx,X878,1021 Jennings Street,Bronx,NY,10460,40.83081,-73.88602,...,2:45 PM,470.0,0.2%,28.5%,70.4%,0.4%,345.0,347.0,339.0,75.0%

In [208]:
#distance and coordinates of students that are assigned to a school
def coordinate_distance():
    coords_1 = [(lat, lon) for lat, lon in zip(df3_new_s['Latitude'], df3_new_s['Longitude'])]
    coords_2 = [(lat, lon) for lat, lon in zip(df2_new_s['Latitude'], df2_new_s['Longitude'])]
    distances = {}
    for c1 in coords_1:
        distances[c1] = [[c2, geopy.distance.geodesic(c1, c2).km] for c2 in coords_2 if geopy.distance.geodesic(c1, c2).km <= 1]
    return distances

In [217]:
student_school_dis = coordinate_distance()
student_school_dis

{(40.81092, -73.95693): [[(40.803001, -73.954098), 0.9112955935580438],
  [(40.809462, -73.949463), 0.6505081780473245],
  [(40.806845, -73.951202), 0.6621005456981693],
  [(40.812462, -73.949507), 0.6492970387891305],
  [(40.802762, -73.953542), 0.9499832971216685],
  [(40.802754, -73.955442), 0.9154866737513924]],
 (40.82776, -73.90039): [[(40.82643, -73.890307), 0.8632766488445531],
  [(40.827672, -73.890905), 0.8001562371931157],
  [(40.829609, -73.896539), 0.3842965363844537],
  [(40.830986, -73.889422), 0.9921102188801794],
  [(40.831084, -73.891492), 0.8364217320436558],
  [(40.828919, -73.891875), 0.7297071442320343],
  [(40.827672, -73.890905), 0.8001562371931157],
  [(40.833056, -73.902872), 0.6242761593453466],
  [(40.824325, -73.898852), 0.4029181443102652],
  [(40.828367, -73.898022), 0.21081612977144829],
  [(40.829992, -73.904943), 0.45709566323568956],
  [(40.831908, -73.894913), 0.6523982617655458],
  [(40.832348, -73.896625), 0.6003735022592903],
  [(40.832348, -73.896625), 0.6003735022592903],
  [(40.822437, -73.906125), 0.7638563446978123],
  [(40.823722, -73.890449), 0.9509522582799378],
  [(40.831828, -73.898144), 0.48987141767613956],
  [(40.821767, -73.895861), 0.767392401435702],
  [(40.823642, -73.890446), 0.9553962914643649],
  [(40.829131, -73.896453), 0.36533406885296305],
  [(40.831243, -73.891401), 0.8511925980247298]],
 (40.74121, -73.87473): [],
 (40.83137, -73.87882): [[(40.835397, -73.886794), 0.8076840186123069],
  [(40.830986, -73.889422), 0.8952894810038224],
  [(40.833004, -73.8851), 0.5599248602326556],
  [(40.827849, -73.88689), 0.785024266602431]],
 (40.64274, -74.07871): [],
 (40.84037, -73.91084): [[(40.846314, -73.914462), 0.7273367236130491],
  [(40.846604, -73.916135), 0.8238156360180469],
  [(40.841459, -73.914056), 0.296967847532156],
  [(40.835477, -73.913453), 0.5863626427973967],
  [(40.845947, -73.915229), 0.7215099586406891],
  [(40.848177, -73.909403), 0.8754031598458664],
  [(40.836684, -73.912075), 0.42237779707025747],
  [(40.837397, -73.914452), 0.4492262404886193],
  [(40.84719, -73.911551), 0.7597369350792903],
  [(40.849361, -73.910872), 0.998462382647301],
  [(40.835974, -73.913561), 0.5394302701808311],
  [(40.842478, -73.914915), 0.4158250770208586],
  [(40.841753, -73.914388), 0.3363405496409101],
  [(40.849041, -73.912561), 0.9737987638505349]],
 (40.77012, -73.95338): [],
 (40.75138, -73.93745): [[(40.748103, -73.94206), 0.532920296645926]],
 (40.84051, -73.83812): [],
 (40.81041, -73.9068): [[(40.812191, -73.90649), 0.19950257422295126],
  [(40.815636, -73.900401), 0.7926514768112302],
  [(40.816096, -73.898955), 0.9147775241581334],
  [(40.811296, -73.9054), 0.1537344857869396],
  [(40.80991, -73.916297), 0.8032414630060556]],
 (40.69114, -73.86843): [],
 (40.85594, -73.92703): [],
 (40.74149, -73.99145): [[(40.740604, -73.98396), 0.6402376461526629],
  [(40.747426, -73.999552), 0.9501467247117311],
  [(40.748126, -73.993533), 0.7576299737775323],
  [(40.746236, -73.984059), 0.8169762892287846],
  [(40.747629, -73.994265), 0.721998330542744],
  [(40.746825, -74.000448), 0.96360993741419],
  [(40.744384, -73.986615), 0.5196617612676184],
  [(40.747629, -73.994265), 0.721998330542744],
  [(40.749131, -73.997019), 0.9701661024194244],
  [(40.748606, -73.987061), 0.8728487100834461]],
 (40.87575, -73.86139): [[(40.878251, -73.853301), 0.7362308317612092],
  [(40.878585, -73.861639), 0.3155299333168797],
  [(40.87597, -73.851408), 0.8417657923830755],
  [(40.871765, -73.857542), 0.5486866792211631],
  [(40.87083, -73.868258), 0.796053835172405],
  [(40.871866, -73.857538), 0.5398836352354027]],
 (40.66823, -73.75684): [[(40.667115, -73.746537), 0.879938980384047]],
 (40.69717, -73.98496): [[(40.689011, -73.981228), 0.9593823767104954],
  [(40.688643, -73.983658), 0.9532797862415403],
  [(40.693835, -73.977916), 0.7011545733068848]],
 (40.74511, -73.99591): [[(40.747426, -73.999552), 0.40094828479046485],
  [(40.748126, -73.993533), 0.39048154044658534],
  [(40.747629, -73.994265), 0.31233351294733874],
  [(40.746825, -74.000448), 0.42797767899752015],
  [(40.744384, -73.986615), 0.78917465466135],
  [(40.747629, -73.994265), 0.31233351294733874],
  [(40.749131, -73.997019), 0.45624539772757755],
  [(40.749501, -73.998444), 0.5325131185124934],
  [(40.748606, -73.987061), 0.8421743403543476]],
 (40.60745, -74.10148): [],
 (40.58413, -73.82568): [],
 (40.73742, -73.85331): [],
 (40.70915, -74.01208): [],
 (40.84181, -73.87542): [[(40.837525, -73.867135), 0.8453888822848766],
  [(40.844998, -73.88389), 0.7972293824457398]],
 (40.68811, -73.97675): [[(40.681447, -73.970879), 0.8909468836086977],
  [(40.688667, -73.976894), 0.06304001158021325],
  [(40.6936, -73.968897), 0.901274395775372],
  [(40.689011, -73.981228), 0.391525407061252],
  [(40.68581, -73.980385), 0.3995641128697886],
  [(40.683104, -73.981208), 0.6716008686539472],
  [(40.685452, -73.974897), 0.33415269350497245],
  [(40.681591, -73.981392), 0.823435935999302],
  [(40.685452, -73.974897), 0.33415269350497245],
  [(40.688643, -73.983658), 0.5869266528511029],
  [(40.693835, -73.977916), 0.6433437048912112]],
 (40.69154, -73.93373): [[(40.692817, -73.938762), 0.448348856587502],
  [(40.69375, -73.929493), 0.4341511913028812],
  [(40.691616, -73.936322), 0.2192542753744021],
  [(40.686892, -73.931765), 0.5422182554625632],
  [(40.696568, -73.924506), 0.9589541535038929],
  [(40.690319, -73.934412), 0.1473354794528016],
  [(40.683619, -73.929187), 0.9597861841428525],
  [(40.688611, -73.942765), 0.8300891737097363],
  [(40.686032, -73.926076), 0.8903449992387483]],
 (40.69696, -73.91082): [[(40.68957, -73.906748), 0.8898981257457267],
  [(40.700335, -73.913751), 0.4492557145577426],
  [(40.695439, -73.922073), 0.9659882088223597],
  [(40.68957, -73.906748), 0.8898981257457267],
  [(40.692473, -73.916809), 0.710293784542927],
  [(40.697836, -73.909171), 0.16996306378340542],
  [(40.68957, -73.906748), 0.8898981257457267]],
 (40.52823, -74.19215): [],
 (40.7099, -73.94366): [[(40.706491, -73.944167), 0.3809802957667077],
  [(40.709877, -73.955324), 0.9856464021358289],
  [(40.705807, -73.943825), 0.4547343719103318],
  [(40.70618, -73.943027), 0.4165484703296655],
  [(40.709289, -73.953719), 0.8527231945801199],
  [(40.709289, -73.953665), 0.8481745580461417],
  [(40.708525, -73.951628), 0.6904227830731752],
  [(40.710602, -73.95479), 0.9437386046641129]],
 (40.77187, -73.78039): [],
 (40.83081, -73.88602): [[(40.82643, -73.890307), 0.6060987386813051],
  [(40.835397, -73.886794), 0.5135559639741215],
  [(40.827672, -73.890905), 0.5396563043696342],
  [(40.829609, -73.896539), 0.8972530990119669],
  [(40.830986, -73.889422), 0.28762302291756237],
  [(40.831084, -73.891492), 0.46256390283862764],
  [(40.828919, -73.891875), 0.5366676420635706],
  [(40.827672, -73.890905), 0.5396563043696342],
  [(40.833004, -73.8851), 0.2557045649551861],
  [(40.827849, -73.88689), 0.3369104859447599],
  [(40.831908, -73.894913), 0.7599637034051592],
  [(40.832348, -73.896625), 0.9106805388970818],
  [(40.832348, -73.896625), 0.9106805388970818],
  [(40.823722, -73.890449), 0.8712917877651087],
  [(40.823642, -73.890446), 0.8792185001631246],
  [(40.829131, -73.896453), 0.8995695308534399],
  [(40.831243, -73.891401), 0.45642562515542306]],
 (40.79056, -73.94445): [[(40.788163, -73.948453), 0.4301240297952271],
  [(40.795722, -73.948545), 0.6693645622171014],
  [(40.797287, -73.948916), 0.8367338051771702],
  [(40.788364, -73.943062), 0.2705449755938539],
  [(40.797229, -73.948165), 0.804226279272984],
  [(40.791403, -73.940332), 0.3599477086686525],
  [(40.788364, -73.943062), 0.2705449755938539],
  [(40.790979, -73.943294), 0.10809434278421721],
  [(40.795832, -73.948758), 0.6891673934477225],
  [(40.794993, -73.935114), 0.9290827851978682],
  [(40.790999, -73.939047), 0.4586152844558362],
  [(40.795209, -73.943435), 0.5233297985971348],
  [(40.788954, -73.950284), 0.5237042183765753],
  [(40.790085, -73.949113), 0.3970821935272979],
  [(40.796713, -73.937102), 0.9227517984034159],
  [(40.795008, -73.948495), 0.6004448414462757],
  [(40.793822, -73.947225), 0.4313631059834541],
  [(40.788954, -73.950284), 0.5237042183765753],
  [(40.786516, -73.942305), 0.48420579462955976],
  [(40.79379, -73.943071), 0.37710086808305254]],
 (40.74509, -73.93681): [[(40.748103, -73.94206), 0.55547447864308]],
 (40.85465, -73.89665): [[(40.856664, -73.893999), 0.3162077028399789],
  [(40.850443, -73.895137), 0.48429824318631354],
  [(40.855583, -73.897879), 0.14654004585770194],
  [(40.853111, -73.89279), 0.36762116627900643],
  [(40.858953, -73.893822), 0.534042358382588],
  [(40.860726, -73.893689), 0.7194533229216779],
  [(40.863011, -73.898475), 0.9411627927751011],
  [(40.853111, -73.89279), 0.36762116627900643],
  [(40.85628, -73.888208), 0.7344735846564956],
  [(40.852134, -73.892766), 0.4304948242233742],
  [(40.852125, -73.907442), 0.9522179184769546],
  [(40.852442, -73.887109), 0.8410449197005888],
  [(40.859681, -73.904257), 0.8506072312423943],
  [(40.857833, -73.893147), 0.46063605889488124],
  [(40.859744, -73.896962), 0.5663058981130771],
  [(40.85869, -73.891129), 0.6465200136645407]],
 (40.71896, -73.97607): [[(40.725179, -73.983238), 0.9185332999222089],
  [(40.727231, -73.97893), 0.9497346038745849],
  [(40.724939, -73.978223), 0.6884258975451726],
  [(40.720291, -73.987298), 0.9601068911914347],
  [(40.725472, -73.98028), 0.8058908250336666],
  [(40.717891, -73.979824), 0.33867064634556915],
  [(40.724319, -73.977549), 0.6080865992665551],
  [(40.717567, -73.979986), 0.3652473776016527],
  [(40.724319, -73.977549), 0.6080865992665551],
  [(40.727253, -73.979612), 0.9683258718897438],
  [(40.722654, -73.984898), 0.8512332127256416],
  [(40.716375, -73.96594), 0.9027710346992274],
  [(40.722913, -73.977899), 0.4653799830584813],
  [(40.719824, -73.9847), 0.735442689619461]],
 (40.81608, -73.93032): [[(40.818491, -73.922269), 0.7301043182465335],
  [(40.810905, -73.927025), 0.6383966128398469],
  [(40.816925, -73.928033), 0.21455796290379697],
  [(40.814275, -73.935337), 0.46834511116007627],
  [(40.819177, -73.921958), 0.7848418062476328],
  [(40.817586, -73.923491), 0.5999291567418352],
  [(40.810905, -73.927025), 0.6383966128398469],
  [(40.815502, -73.935614), 0.45123796334921185],
  [(40.817586, -73.941234), 0.9358534908676158],
  [(40.819514, -73.938031), 0.7540825218656702],
  [(40.811124, -73.939683), 0.9627871182495659]],
 (40.87706, -73.88978): [[(40.87719, -73.889569), 0.02290721669088332]],
 (40.64184, -73.89869): [],
 (40.8223, -73.85596): [[(40.822154, -73.862172), 0.5243002618901118]],
 (40.78574, -73.97442): [[(40.787072, -73.9792), 0.4297221646845636],
  [(40.791258, -73.967772), 0.8308673223988686]],
 (40.69288, -73.82931): [],
 (40.67986, -74.00148): [[(40.677662, -74.006367), 0.479871166398302],
  [(40.679663, -74.009338), 0.6646839170068889],
  [(40.678883, -74.009601), 0.6950815865850414],
  [(40.67789, -74.001089), 0.221247324280865],
  [(40.67789, -74.001089), 0.221247324280865],
  [(40.677882, -74.00106), 0.22250384027707137],
  [(40.677863, -74.003674), 0.28910797536494315]],
 (40.72264, -73.95258): [[(40.715286, -73.958303), 0.949070016960623],
  [(40.727462, -73.951618), 0.5416089732459203]],
 (40.81523, -73.9552): [[(40.809462, -73.949463), 0.8028656817637909],
  [(40.806845, -73.951202), 0.9903760174079759],
  [(40.813539, -73.94498), 0.8824805603530887],
  [(40.812462, -73.949507), 0.5702636713562418],
  [(40.820352, -73.945556), 0.9927373666703274],
  [(40.820348, -73.955687), 0.5698390192051861],
  [(40.813095, -73.945331), 0.865755180621176],
  [(40.816423, -73.944251), 0.9332074420387133],
  [(40.820334, -73.955651), 0.5680768627730203]],
 (40.74289, -74.00213): [[(40.747426, -73.999552), 0.5487622606484415],
  [(40.748126, -73.993533), 0.9302078482799194],
  [(40.747629, -73.994265), 0.8474656012522489],
  [(40.746825, -74.000448), 0.459489382983778],
  [(40.747629, -73.994265), 0.8474656012522489],
  [(40.749131, -73.997019), 0.8164920862839056],
  [(40.749501, -73.998444), 0.7974221241419838]]}

In [ ]:
def school_student_distance(distance_list):
    lst = {}
    for i in range(len(df3_new_s['School Name'])):
        lst[df3_new_s['School Name'][i]] = distance_list
    return lst

In [210]:
#distance and coordinates of bus stops that are assigned to a school
def coordinate_distance_2():
    coords_1 = [(lat, lon) for lat, lon in zip(df3_new_s['Latitude'], df3_new_s['Longitude'])]
    coords_2 = [(lat, lon) for lat, lon in zip(df1_new_s['Latitude'], df1_new_s['Longitude'])]
    distances = {}
    for c1 in coords_1:
        distances[c1] = [[c2, geopy.distance.geodesic(c1, c2).km] for c2 in coords_2 if geopy.distance.geodesic(c1, c2).km <= 1]
    return distances

In [216]:
stop_school_dis = coordinate_distance_2()
stop_school_dis

{(40.81092, -73.95693): [[(40.812874, -73.949044), 0.6998617960841147],
  [(40.81384, -73.956494), 0.3263468106244565],
  [(40.810537, -73.952317), 0.39154068405628384],
  [(40.808032, -73.945816), 0.9910911538602701],
  [(40.811627, -73.961497), 0.39325641015669904],
  [(40.816135, -73.954403), 0.6171272107797243],
  [(40.805321, -73.966098), 0.9924868768680932]],
 (40.82776, -73.90039): [[(40.827654, -73.898451), 0.1639852347170781],
  [(40.833677, -73.896573), 0.7317265870846529],
  [(40.835184, -73.893692), 0.9994463184874849],
  [(40.825224, -73.891469), 0.8035053388614369],
  [(40.827371, -73.904648), 0.36176807013384876]],
 (40.74121, -73.87473): [[(40.742029, -73.867697), 0.6009495461880412],
  [(40.733131, -73.87111), 0.9478403479291088],
  [(40.73691, -73.865842), 0.8897296178650793],
  [(40.735753, -73.880849), 0.7964703008502216]],
 (40.83137, -73.87882): [[(40.840077, -73.877143), 0.9772094857729251],
  [(40.83609, -73.883724), 0.6677095818413458]],
 (40.64274, -74.07871): [],
 (40.84037, -73.91084): [[(40.837051, -73.908246), 0.4286177391948797],
  [(40.838419, -73.90142), 0.8234869527941483],
  [(40.837071, -73.909064), 0.3957947608810176],
  [(40.837051, -73.908246), 0.4286177391948797]],
 (40.77012, -73.95338): [[(40.778101, -73.95178), 0.8965203927466063],
  [(40.771608, -73.950711), 0.2794272887536501],
  [(40.768021, -73.95627), 0.33744178291165305],
  [(40.766086, -73.960501), 0.7497649927145611],
  [(40.771608, -73.950711), 0.2794272887536501],
  [(40.763493, -73.956358), 0.7776918138709609],
  [(40.769589, -73.951606), 0.16096373135265918],
  [(40.765961, -73.960592), 0.7642481318242536],
  [(40.768021, -73.95627), 0.33744178291165305],
  [(40.766086, -73.960501), 0.7497649927145611],
  [(40.771595, -73.950665), 0.28172661569122004]],
 (40.75138, -73.93745): [],
 (40.84051, -73.83812): [],
 (40.81041, -73.9068): [[(40.813059, -73.90877), 0.3378836574725927],
  [(40.812135, -73.914305), 0.6615730798219934],
  [(40.813636, -73.910427), 0.47116051836768436],
  [(40.813636, -73.910427), 0.47116051836768436]],
 (40.69114, -73.86843): [[(40.683101, -73.866056), 0.9149916658964216],
  [(40.691426, -73.866977), 0.12685702365841425]],
 (40.85594, -73.92703): [[(40.85487, -73.937071), 0.8549426381804359]],
 (40.74149, -73.99145): [[(40.733818, -73.989734), 0.8642088129264592],
  [(40.741317, -73.989891), 0.13307213165603907],
  [(40.73908, -73.983136), 0.7515074813559379],
  [(40.737902, -73.981214), 0.951980975576142],
  [(40.740017, -74.002919), 0.9824307338000889],
  [(40.745548, -73.99886), 0.7712096499634535],
  [(40.73301, -73.987564), 0.997262283455417]],
 (40.87575, -73.86139): [[(40.872479, -73.851401), 0.9170351181455433],
  [(40.871056, -73.861527), 0.521403470792104],
  [(40.872831, -73.85182), 0.8693944180576978]],
 (40.66823, -73.75684): [],
 (40.69717, -73.98496): [[(40.690543, -73.989365), 0.8247405017234196],
  [(40.698276, -73.982605), 0.2338841305421208],
  [(40.689355, -73.985244), 0.8681719205558106],
  [(40.69595, -73.990913), 0.521067227867902],
  [(40.689723, -73.983149), 0.8410218837838355]],
 (40.74511, -73.99591): [[(40.741317, -73.989891), 0.6601944797339665],
  [(40.740017, -74.002919), 0.8187346643517407],
  [(40.745548, -73.99886), 0.2538549755419164]],
 (40.60745, -74.10148): [],
 (40.58413, -73.82568): [[(40.582038, -73.829007), 0.3651127074597645]],
 (40.73742, -73.85331): [[(40.743654, -73.855795), 0.7233984475648636],
  [(40.731336, -73.848904), 0.7713521951206055]],
 (40.70915, -74.01208): [[(40.708184, -74.01258), 0.11529385942874554]],
 (40.84181, -73.87542): [[(40.84406, -73.865572), 0.867298946414423],
  [(40.846021, -73.884755), 0.9156681759008077],
  [(40.840077, -73.877143), 0.24114984903487863],
  [(40.83609, -73.883724), 0.9455112564294458],
  [(40.840676, -73.864393), 0.9384688693869845]],
 (40.68811, -73.97675): [[(40.689355, -73.985244), 0.7311854229312792],
  [(40.689723, -73.983149), 0.569790835759915],
  [(40.681641, -73.976815), 0.7183893734566982]],
 (40.69154, -73.93373): [[(40.688998, -73.930369), 0.4004944523272057],
  [(40.684141, -73.929003), 0.9136518876788604],
  [(40.688871, -73.926901), 0.6488854225119787],
  [(40.69027, -73.945377), 0.9945362570169013]],
 (40.69696, -73.91082): [[(40.696653, -73.915132), 0.3660393298646767]],
 (40.52823, -74.19215): [],
 (40.7099, -73.94366): [[(40.706872, -73.943041), 0.34029848007542723],
  [(40.715978, -73.940148), 0.7373108184159286],
  [(40.702976, -73.945783), 0.789551629357813]],
 (40.77187, -73.78039): [],
 (40.83081, -73.88602): [[(40.833677, -73.896573), 0.9453525704974065],
  [(40.835184, -73.893692), 0.8091307751663019],
  [(40.83609, -73.883724), 0.6175011634520015],
  [(40.825224, -73.891469), 0.7720612023932405]],
 (40.79056, -73.94445): [[(40.790869, -73.942429), 0.173991205204136],
  [(40.787422, -73.947546), 0.43556638567007805],
  [(40.782671, -73.948406), 0.9375486902281004],
  [(40.784504, -73.947414), 0.7175429244616355],
  [(40.793388, -73.949529), 0.5313935095243159],
  [(40.787422, -73.947546), 0.43556638567007805],
  [(40.795858, -73.938818), 0.7563615573277203],
  [(40.787168, -73.953762), 0.8715642453648927]],
 (40.74509, -73.93681): [],
 (40.85465, -73.89665): [[(40.848087, -73.900912), 0.8126193768300518],
  [(40.852055, -73.903581), 0.6516183746826529],
  [(40.8558, -73.901267), 0.409712957181128],
  [(40.860263, -73.891171), 0.7758577297975083],
  [(40.8558, -73.901267), 0.409712957181128],
  [(40.86251, -73.897871), 0.8789123068681014],
  [(40.862464, -73.900526), 0.9272527851935679]],
 (40.71896, -73.97607): [[(40.725168, -73.975629), 0.6903954581585574],
  [(40.716474, -73.980305), 0.4519444689583926],
  [(40.723087, -73.979467), 0.5407499124100933],
  [(40.713462, -73.982304), 0.8063630313448914]],
 (40.81608, -73.93032): [[(40.81041, -73.937101), 0.8507620750559707],
  [(40.816469, -73.939329), 0.7613013103234048],
  [(40.821187, -73.93605), 0.7452048206959839],
  [(40.811462, -73.927591), 0.5621476596968266],
  [(40.812823, -73.925757), 0.52823532713127],
  [(40.814448, -73.936259), 0.5328399028107897],
  [(40.817602, -73.923121), 0.6304417950066225],
  [(40.815011, -73.936132), 0.5045197201568846],
  [(40.813812, -73.940424), 0.8889028761119524]],
 (40.87706, -73.88978): [[(40.871993, -73.882629), 0.8246119952114184],
  [(40.87956, -73.885606), 0.448172829888798],
  [(40.876716, -73.889717), 0.038569053197451186]],
 (40.64184, -73.89869): [[(40.640487, -73.906077), 0.6426743649738188]],
 (40.8223, -73.85596): [[(40.817193, -73.84745), 0.9149184437019313],
  [(40.827698, -73.849723), 0.7975969805574872],
  [(40.824712, -73.858864), 0.3629882203804957]],
 (40.78574, -73.97442): [[(40.791345, -73.96878), 0.7836034910021884],
  [(40.791017, -73.972419), 0.6098623185045083],
  [(40.781084, -73.97627), 0.5401144381393722]],
 (40.69288, -73.82931): [[(40.692842, -73.831814), 0.21169148548799713],
  [(40.688246, -73.819201), 0.9974761181871626],
  [(40.701705, -73.831562), 0.9983117502477569],
  [(40.698176, -73.835156), 0.7681270525604454],
  [(40.700017, -73.830529), 0.7992186785866497],
  [(40.690527, -73.824257), 0.5006978417565291],
  [(40.696271, -73.838195), 0.8401030006382346],
  [(40.701705, -73.831562), 0.9983117502477569],
  [(40.691894, -73.819462), 0.8395738891494731]],
 (40.67986, -74.00148): [[(40.682848, -74.003843), 0.38730442309105567]],
 (40.72264, -73.95258): [],
 (40.81523, -73.9552): [[(40.812874, -73.949044), 0.5815648144231923],
  [(40.81384, -73.956494), 0.18906689645612146],
  [(40.810537, -73.952317), 0.5751308960668471],
  [(40.811627, -73.961497), 0.6651021501895489],
  [(40.820098, -73.946484), 0.9126692557932937],
  [(40.820098, -73.946484), 0.9126692557932937],
  [(40.816135, -73.954403), 0.12092094965897775],
  [(40.821104, -73.957165), 0.6730461260375549],
  [(40.823131, -73.953102), 0.8950838545234628]],
 (40.74289, -74.00213): [[(40.740017, -74.002919), 0.32592920576732426],
  [(40.745548, -73.99886), 0.4042291690510437]]}

In [240]:
lst1_grouped = {} 
for key,val in student_school_dis.items():
    lst = []
    for sublist in val:
        lst.append(sublist[0])
    lst1_grouped[key] = lst

lst1_grouped

{(40.81092, -73.95693): [(40.803001, -73.954098),
  (40.809462, -73.949463),
  (40.806845, -73.951202),
  (40.812462, -73.949507),
  (40.802762, -73.953542),
  (40.802754, -73.955442)],
 (40.82776, -73.90039): [(40.82643, -73.890307),
  (40.827672, -73.890905),
  (40.829609, -73.896539),
  (40.830986, -73.889422),
  (40.831084, -73.891492),
  (40.828919, -73.891875),
  (40.827672, -73.890905),
  (40.833056, -73.902872),
  (40.824325, -73.898852),
  (40.828367, -73.898022),
  (40.829992, -73.904943),
  (40.831908, -73.894913),
  (40.832348, -73.896625),
  (40.832348, -73.896625),
  (40.822437, -73.906125),
  (40.823722, -73.890449),
  (40.831828, -73.898144),
  (40.821767, -73.895861),
  (40.823642, -73.890446),
  (40.829131, -73.896453),
  (40.831243, -73.891401)],
 (40.74121, -73.87473): [],
 (40.83137, -73.87882): [(40.835397, -73.886794),
  (40.830986, -73.889422),
  (40.833004, -73.8851),
  (40.827849, -73.88689)],
 (40.64274, -74.07871): [],
 (40.84037, -73.91084): [(40.846314, -73.914462),
  (40.846604, -73.916135),
  (40.841459, -73.914056),
  (40.835477, -73.913453),
  (40.845947, -73.915229),
  (40.848177, -73.909403),
  (40.836684, -73.912075),
  (40.837397, -73.914452),
  (40.84719, -73.911551),
  (40.849361, -73.910872),
  (40.835974, -73.913561),
  (40.842478, -73.914915),
  (40.841753, -73.914388),
  (40.849041, -73.912561)],
 (40.77012, -73.95338): [],
 (40.75138, -73.93745): [(40.748103, -73.94206)],
 (40.84051, -73.83812): [],
 (40.81041, -73.9068): [(40.812191, -73.90649),
  (40.815636, -73.900401),
  (40.816096, -73.898955),
  (40.811296, -73.9054),
  (40.80991, -73.916297)],
 (40.69114, -73.86843): [],
 (40.85594, -73.92703): [],
 (40.74149, -73.99145): [(40.740604, -73.98396),
  (40.747426, -73.999552),
  (40.748126, -73.993533),
  (40.746236, -73.984059),
  (40.747629, -73.994265),
  (40.746825, -74.000448),
  (40.744384, -73.986615),
  (40.747629, -73.994265),
  (40.749131, -73.997019),
  (40.748606, -73.987061)],
 (40.87575, -73.86139): [(40.878251, -73.853301),
  (40.878585, -73.861639),
  (40.87597, -73.851408),
  (40.871765, -73.857542),
  (40.87083, -73.868258),
  (40.871866, -73.857538)],
 (40.66823, -73.75684): [(40.667115, -73.746537)],
 (40.69717, -73.98496): [(40.689011, -73.981228),
  (40.688643, -73.983658),
  (40.693835, -73.977916)],
 (40.74511, -73.99591): [(40.747426, -73.999552),
  (40.748126, -73.993533),
  (40.747629, -73.994265),
  (40.746825, -74.000448),
  (40.744384, -73.986615),
  (40.747629, -73.994265),
  (40.749131, -73.997019),
  (40.749501, -73.998444),
  (40.748606, -73.987061)],
 (40.60745, -74.10148): [],
 (40.58413, -73.82568): [],
 (40.73742, -73.85331): [],
 (40.70915, -74.01208): [],
 (40.84181, -73.87542): [(40.837525, -73.867135), (40.844998, -73.88389)],
 (40.68811, -73.97675): [(40.681447, -73.970879),
  (40.688667, -73.976894),
  (40.6936, -73.968897),
  (40.689011, -73.981228),
  (40.68581, -73.980385),
  (40.683104, -73.981208),
  (40.685452, -73.974897),
  (40.681591, -73.981392),
  (40.685452, -73.974897),
  (40.688643, -73.983658),
  (40.693835, -73.977916)],
 (40.69154, -73.93373): [(40.692817, -73.938762),
  (40.69375, -73.929493),
  (40.691616, -73.936322),
  (40.686892, -73.931765),
  (40.696568, -73.924506),
  (40.690319, -73.934412),
  (40.683619, -73.929187),
  (40.688611, -73.942765),
  (40.686032, -73.926076)],
 (40.69696, -73.91082): [(40.68957, -73.906748),
  (40.700335, -73.913751),
  (40.695439, -73.922073),
  (40.68957, -73.906748),
  (40.692473, -73.916809),
  (40.697836, -73.909171),
  (40.68957, -73.906748)],
 (40.52823, -74.19215): [],
 (40.7099, -73.94366): [(40.706491, -73.944167),
  (40.709877, -73.955324),
  (40.705807, -73.943825),
  (40.70618, -73.943027),
  (40.709289, -73.953719),
  (40.709289, -73.953665),
  (40.708525, -73.951628),
  (40.710602, -73.95479)],
 (40.77187, -73.78039): [],
 (40.83081, -73.88602): [(40.82643, -73.890307),
  (40.835397, -73.886794),
  (40.827672, -73.890905),
  (40.829609, -73.896539),
  (40.830986, -73.889422),
  (40.831084, -73.891492),
  (40.828919, -73.891875),
  (40.827672, -73.890905),
  (40.833004, -73.8851),
  (40.827849, -73.88689),
  (40.831908, -73.894913),
  (40.832348, -73.896625),
  (40.832348, -73.896625),
  (40.823722, -73.890449),
  (40.823642, -73.890446),
  (40.829131, -73.896453),
  (40.831243, -73.891401)],
 (40.79056, -73.94445): [(40.788163, -73.948453),
  (40.795722, -73.948545),
  (40.797287, -73.948916),
  (40.788364, -73.943062),
  (40.797229, -73.948165),
  (40.791403, -73.940332),
  (40.788364, -73.943062),
  (40.790979, -73.943294),
  (40.795832, -73.948758),
  (40.794993, -73.935114),
  (40.790999, -73.939047),
  (40.795209, -73.943435),
  (40.788954, -73.950284),
  (40.790085, -73.949113),
  (40.796713, -73.937102),
  (40.795008, -73.948495),
  (40.793822, -73.947225),
  (40.788954, -73.950284),
  (40.786516, -73.942305),
  (40.79379, -73.943071)],
 (40.74509, -73.93681): [(40.748103, -73.94206)],
 (40.85465, -73.89665): [(40.856664, -73.893999),
  (40.850443, -73.895137),
  (40.855583, -73.897879),
  (40.853111, -73.89279),
  (40.858953, -73.893822),
  (40.860726, -73.893689),
  (40.863011, -73.898475),
  (40.853111, -73.89279),
  (40.85628, -73.888208),
  (40.852134, -73.892766),
  (40.852125, -73.907442),
  (40.852442, -73.887109),
  (40.859681, -73.904257),
  (40.857833, -73.893147),
  (40.859744, -73.896962),
  (40.85869, -73.891129)],
 (40.71896, -73.97607): [(40.725179, -73.983238),
  (40.727231, -73.97893),
  (40.724939, -73.978223),
  (40.720291, -73.987298),
  (40.725472, -73.98028),
  (40.717891, -73.979824),
  (40.724319, -73.977549),
  (40.717567, -73.979986),
  (40.724319, -73.977549),
  (40.727253, -73.979612),
  (40.722654, -73.984898),
  (40.716375, -73.96594),
  (40.722913, -73.977899),
  (40.719824, -73.9847)],
 (40.81608, -73.93032): [(40.818491, -73.922269),
  (40.810905, -73.927025),
  (40.816925, -73.928033),
  (40.814275, -73.935337),
  (40.819177, -73.921958),
  (40.817586, -73.923491),
  (40.810905, -73.927025),
  (40.815502, -73.935614),
  (40.817586, -73.941234),
  (40.819514, -73.938031),
  (40.811124, -73.939683)],
 (40.87706, -73.88978): [(40.87719, -73.889569)],
 (40.64184, -73.89869): [],
 (40.8223, -73.85596): [(40.822154, -73.862172)],
 (40.78574, -73.97442): [(40.787072, -73.9792), (40.791258, -73.967772)],
 (40.69288, -73.82931): [],
 (40.67986, -74.00148): [(40.677662, -74.006367),
  (40.679663, -74.009338),
  (40.678883, -74.009601),
  (40.67789, -74.001089),
  (40.67789, -74.001089),
  (40.677882, -74.00106),
  (40.677863, -74.003674)],
 (40.72264, -73.95258): [(40.715286, -73.958303), (40.727462, -73.951618)],
 (40.81523, -73.9552): [(40.809462, -73.949463),
  (40.806845, -73.951202),
  (40.813539, -73.94498),
  (40.812462, -73.949507),
  (40.820352, -73.945556),
  (40.820348, -73.955687),
  (40.813095, -73.945331),
  (40.816423, -73.944251),
  (40.820334, -73.955651)],
 (40.74289, -74.00213): [(40.747426, -73.999552),
  (40.748126, -73.993533),
  (40.747629, -73.994265),
  (40.746825, -74.000448),
  (40.747629, -73.994265),
  (40.749131, -73.997019),
  (40.749501, -73.998444)]}

In [241]:
lst2_grouped = {} 
for key,val in stop_school_dis.items():
    lst = []
    for sublist in val:
        lst.append(sublist[0])
    lst2_grouped[key] = lst

lst2_grouped

{(40.81092, -73.95693): [(40.812874, -73.949044),
  (40.81384, -73.956494),
  (40.810537, -73.952317),
  (40.808032, -73.945816),
  (40.811627, -73.961497),
  (40.816135, -73.954403),
  (40.805321, -73.966098)],
 (40.82776, -73.90039): [(40.827654, -73.898451),
  (40.833677, -73.896573),
  (40.835184, -73.893692),
  (40.825224, -73.891469),
  (40.827371, -73.904648)],
 (40.74121, -73.87473): [(40.742029, -73.867697),
  (40.733131, -73.87111),
  (40.73691, -73.865842),
  (40.735753, -73.880849)],
 (40.83137, -73.87882): [(40.840077, -73.877143), (40.83609, -73.883724)],
 (40.64274, -74.07871): [],
 (40.84037, -73.91084): [(40.837051, -73.908246),
  (40.838419, -73.90142),
  (40.837071, -73.909064),
  (40.837051, -73.908246)],
 (40.77012, -73.95338): [(40.778101, -73.95178),
  (40.771608, -73.950711),
  (40.768021, -73.95627),
  (40.766086, -73.960501),
  (40.771608, -73.950711),
  (40.763493, -73.956358),
  (40.769589, -73.951606),
  (40.765961, -73.960592),
  (40.768021, -73.95627),
  (40.766086, -73.960501),
  (40.771595, -73.950665)],
 (40.75138, -73.93745): [],
 (40.84051, -73.83812): [],
 (40.81041, -73.9068): [(40.813059, -73.90877),
  (40.812135, -73.914305),
  (40.813636, -73.910427),
  (40.813636, -73.910427)],
 (40.69114, -73.86843): [(40.683101, -73.866056), (40.691426, -73.866977)],
 (40.85594, -73.92703): [(40.85487, -73.937071)],
 (40.74149, -73.99145): [(40.733818, -73.989734),
  (40.741317, -73.989891),
  (40.73908, -73.983136),
  (40.737902, -73.981214),
  (40.740017, -74.002919),
  (40.745548, -73.99886),
  (40.73301, -73.987564)],
 (40.87575, -73.86139): [(40.872479, -73.851401),
  (40.871056, -73.861527),
  (40.872831, -73.85182)],
 (40.66823, -73.75684): [],
 (40.69717, -73.98496): [(40.690543, -73.989365),
  (40.698276, -73.982605),
  (40.689355, -73.985244),
  (40.69595, -73.990913),
  (40.689723, -73.983149)],
 (40.74511, -73.99591): [(40.741317, -73.989891),
  (40.740017, -74.002919),
  (40.745548, -73.99886)],
 (40.60745, -74.10148): [],
 (40.58413, -73.82568): [(40.582038, -73.829007)],
 (40.73742, -73.85331): [(40.743654, -73.855795), (40.731336, -73.848904)],
 (40.70915, -74.01208): [(40.708184, -74.01258)],
 (40.84181, -73.87542): [(40.84406, -73.865572),
  (40.846021, -73.884755),
  (40.840077, -73.877143),
  (40.83609, -73.883724),
  (40.840676, -73.864393)],
 (40.68811, -73.97675): [(40.689355, -73.985244),
  (40.689723, -73.983149),
  (40.681641, -73.976815)],
 (40.69154, -73.93373): [(40.688998, -73.930369),
  (40.684141, -73.929003),
  (40.688871, -73.926901),
  (40.69027, -73.945377)],
 (40.69696, -73.91082): [(40.696653, -73.915132)],
 (40.52823, -74.19215): [],
 (40.7099, -73.94366): [(40.706872, -73.943041),
  (40.715978, -73.940148),
  (40.702976, -73.945783)],
 (40.77187, -73.78039): [],
 (40.83081, -73.88602): [(40.833677, -73.896573),
  (40.835184, -73.893692),
  (40.83609, -73.883724),
  (40.825224, -73.891469)],
 (40.79056, -73.94445): [(40.790869, -73.942429),
  (40.787422, -73.947546),
  (40.782671, -73.948406),
  (40.784504, -73.947414),
  (40.793388, -73.949529),
  (40.787422, -73.947546),
  (40.795858, -73.938818),
  (40.787168, -73.953762)],
 (40.74509, -73.93681): [],
 (40.85465, -73.89665): [(40.848087, -73.900912),
  (40.852055, -73.903581),
  (40.8558, -73.901267),
  (40.860263, -73.891171),
  (40.8558, -73.901267),
  (40.86251, -73.897871),
  (40.862464, -73.900526)],
 (40.71896, -73.97607): [(40.725168, -73.975629),
  (40.716474, -73.980305),
  (40.723087, -73.979467),
  (40.713462, -73.982304)],
 (40.81608, -73.93032): [(40.81041, -73.937101),
  (40.816469, -73.939329),
  (40.821187, -73.93605),
  (40.811462, -73.927591),
  (40.812823, -73.925757),
  (40.814448, -73.936259),
  (40.817602, -73.923121),
  (40.815011, -73.936132),
  (40.813812, -73.940424)],
 (40.87706, -73.88978): [(40.871993, -73.882629),
  (40.87956, -73.885606),
  (40.876716, -73.889717)],
 (40.64184, -73.89869): [(40.640487, -73.906077)],
 (40.8223, -73.85596): [(40.817193, -73.84745),
  (40.827698, -73.849723),
  (40.824712, -73.858864)],
 (40.78574, -73.97442): [(40.791345, -73.96878),
  (40.791017, -73.972419),
  (40.781084, -73.97627)],
 (40.69288, -73.82931): [(40.692842, -73.831814),
  (40.688246, -73.819201),
  (40.701705, -73.831562),
  (40.698176, -73.835156),
  (40.700017, -73.830529),
  (40.690527, -73.824257),
  (40.696271, -73.838195),
  (40.701705, -73.831562),
  (40.691894, -73.819462)],
 (40.67986, -74.00148): [(40.682848, -74.003843)],
 (40.72264, -73.95258): [],
 (40.81523, -73.9552): [(40.812874, -73.949044),
  (40.81384, -73.956494),
  (40.810537, -73.952317),
  (40.811627, -73.961497),
  (40.820098, -73.946484),
  (40.820098, -73.946484),
  (40.816135, -73.954403),
  (40.821104, -73.957165),
  (40.823131, -73.953102)],
 (40.74289, -74.00213): [(40.740017, -74.002919), (40.745548, -73.99886)]}

In [255]:
#groups the students assigned to each school
lst1_grouped_1 = []
for val in student_school_dis.values():
    lst = []
    for sublist in val:
        lst.append(sublist[0])
    lst1_grouped_1.append(lst)

lst1_grouped_1

[[(40.803001, -73.954098),
  (40.809462, -73.949463),
  (40.806845, -73.951202),
  (40.812462, -73.949507),
  (40.802762, -73.953542),
  (40.802754, -73.955442)],
 [(40.82643, -73.890307),
  (40.827672, -73.890905),
  (40.829609, -73.896539),
  (40.830986, -73.889422),
  (40.831084, -73.891492),
  (40.828919, -73.891875),
  (40.827672, -73.890905),
  (40.833056, -73.902872),
  (40.824325, -73.898852),
  (40.828367, -73.898022),
  (40.829992, -73.904943),
  (40.831908, -73.894913),
  (40.832348, -73.896625),
  (40.832348, -73.896625),
  (40.822437, -73.906125),
  (40.823722, -73.890449),
  (40.831828, -73.898144),
  (40.821767, -73.895861),
  (40.823642, -73.890446),
  (40.829131, -73.896453),
  (40.831243, -73.891401)],
 [],
 [(40.835397, -73.886794),
  (40.830986, -73.889422),
  (40.833004, -73.8851),
  (40.827849, -73.88689)],
 [],
 [(40.846314, -73.914462),
  (40.846604, -73.916135),
  (40.841459, -73.914056),
  (40.835477, -73.913453),
  (40.845947, -73.915229),
  (40.848177, -73.909403),
  (40.836684, -73.912075),
  (40.837397, -73.914452),
  (40.84719, -73.911551),
  (40.849361, -73.910872),
  (40.835974, -73.913561),
  (40.842478, -73.914915),
  (40.841753, -73.914388),
  (40.849041, -73.912561)],
 [],
 [(40.748103, -73.94206)],
 [],
 [(40.812191, -73.90649),
  (40.815636, -73.900401),
  (40.816096, -73.898955),
  (40.811296, -73.9054),
  (40.80991, -73.916297)],
 [],
 [],
 [(40.740604, -73.98396),
  (40.747426, -73.999552),
  (40.748126, -73.993533),
  (40.746236, -73.984059),
  (40.747629, -73.994265),
  (40.746825, -74.000448),
  (40.744384, -73.986615),
  (40.747629, -73.994265),
  (40.749131, -73.997019),
  (40.748606, -73.987061)],
 [(40.878251, -73.853301),
  (40.878585, -73.861639),
  (40.87597, -73.851408),
  (40.871765, -73.857542),
  (40.87083, -73.868258),
  (40.871866, -73.857538)],
 [(40.667115, -73.746537)],
 [(40.689011, -73.981228), (40.688643, -73.983658), (40.693835, -73.977916)],
 [(40.747426, -73.999552),
  (40.748126, -73.993533),
  (40.747629, -73.994265),
  (40.746825, -74.000448),
  (40.744384, -73.986615),
  (40.747629, -73.994265),
  (40.749131, -73.997019),
  (40.749501, -73.998444),
  (40.748606, -73.987061)],
 [],
 [],
 [],
 [],
 [(40.837525, -73.867135), (40.844998, -73.88389)],
 [(40.681447, -73.970879),
  (40.688667, -73.976894),
  (40.6936, -73.968897),
  (40.689011, -73.981228),
  (40.68581, -73.980385),
  (40.683104, -73.981208),
  (40.685452, -73.974897),
  (40.681591, -73.981392),
  (40.685452, -73.974897),
  (40.688643, -73.983658),
  (40.693835, -73.977916)],
 [(40.692817, -73.938762),
  (40.69375, -73.929493),
  (40.691616, -73.936322),
  (40.686892, -73.931765),
  (40.696568, -73.924506),
  (40.690319, -73.934412),
  (40.683619, -73.929187),
  (40.688611, -73.942765),
  (40.686032, -73.926076)],
 [(40.68957, -73.906748),
  (40.700335, -73.913751),
  (40.695439, -73.922073),
  (40.68957, -73.906748),
  (40.692473, -73.916809),
  (40.697836, -73.909171),
  (40.68957, -73.906748)],
 [],
 [(40.706491, -73.944167),
  (40.709877, -73.955324),
  (40.705807, -73.943825),
  (40.70618, -73.943027),
  (40.709289, -73.953719),
  (40.709289, -73.953665),
  (40.708525, -73.951628),
  (40.710602, -73.95479)],
 [],
 [(40.82643, -73.890307),
  (40.835397, -73.886794),
  (40.827672, -73.890905),
  (40.829609, -73.896539),
  (40.830986, -73.889422),
  (40.831084, -73.891492),
  (40.828919, -73.891875),
  (40.827672, -73.890905),
  (40.833004, -73.8851),
  (40.827849, -73.88689),
  (40.831908, -73.894913),
  (40.832348, -73.896625),
  (40.832348, -73.896625),
  (40.823722, -73.890449),
  (40.823642, -73.890446),
  (40.829131, -73.896453),
  (40.831243, -73.891401)],
 [(40.788163, -73.948453),
  (40.795722, -73.948545),
  (40.797287, -73.948916),
  (40.788364, -73.943062),
  (40.797229, -73.948165),
  (40.791403, -73.940332),
  (40.788364, -73.943062),
  (40.790979, -73.943294),
  (40.795832, -73.948758),
  (40.794993, -73.935114),
  (40.790999, -73.939047),
  (40.795209, -73.943435),
  (40.788954, -73.950284),
  (40.790085, -73.949113),
  (40.796713, -73.937102),
  (40.795008, -73.948495),
  (40.793822, -73.947225),
  (40.788954, -73.950284),
  (40.786516, -73.942305),
  (40.79379, -73.943071)],
 [(40.748103, -73.94206)],
 [(40.856664, -73.893999),
  (40.850443, -73.895137),
  (40.855583, -73.897879),
  (40.853111, -73.89279),
  (40.858953, -73.893822),
  (40.860726, -73.893689),
  (40.863011, -73.898475),
  (40.853111, -73.89279),
  (40.85628, -73.888208),
  (40.852134, -73.892766),
  (40.852125, -73.907442),
  (40.852442, -73.887109),
  (40.859681, -73.904257),
  (40.857833, -73.893147),
  (40.859744, -73.896962),
  (40.85869, -73.891129)],
 [(40.725179, -73.983238),
  (40.727231, -73.97893),
  (40.724939, -73.978223),
  (40.720291, -73.987298),
  (40.725472, -73.98028),
  (40.717891, -73.979824),
  (40.724319, -73.977549),
  (40.717567, -73.979986),
  (40.724319, -73.977549),
  (40.727253, -73.979612),
  (40.722654, -73.984898),
  (40.716375, -73.96594),
  (40.722913, -73.977899),
  (40.719824, -73.9847)],
 [(40.818491, -73.922269),
  (40.810905, -73.927025),
  (40.816925, -73.928033),
  (40.814275, -73.935337),
  (40.819177, -73.921958),
  (40.817586, -73.923491),
  (40.810905, -73.927025),
  (40.815502, -73.935614),
  (40.817586, -73.941234),
  (40.819514, -73.938031),
  (40.811124, -73.939683)],
 [(40.87719, -73.889569)],
 [],
 [(40.822154, -73.862172)],
 [(40.787072, -73.9792), (40.791258, -73.967772)],
 [],
 [(40.677662, -74.006367),
  (40.679663, -74.009338),
  (40.678883, -74.009601),
  (40.67789, -74.001089),
  (40.67789, -74.001089),
  (40.677882, -74.00106),
  (40.677863, -74.003674)],
 [(40.715286, -73.958303), (40.727462, -73.951618)],
 [(40.809462, -73.949463),
  (40.806845, -73.951202),
  (40.813539, -73.94498),
  (40.812462, -73.949507),
  (40.820352, -73.945556),
  (40.820348, -73.955687),
  (40.813095, -73.945331),
  (40.816423, -73.944251),
  (40.820334, -73.955651)],
 [(40.747426, -73.999552),
  (40.748126, -73.993533),
  (40.747629, -73.994265),
  (40.746825, -74.000448),
  (40.747629, -73.994265),
  (40.749131, -73.997019),
  (40.749501, -73.998444)]]

In [429]:
#groups the stops within the region of each school
lst2_grouped_2 = []
for val in stop_school_dis.values():
    lst = []
    for sublist in val:
        lst.append(sublist[0])
    lst2_grouped_2.append(lst)

lst2_grouped_2

[[(40.812874, -73.949044),
  (40.81384, -73.956494),
  (40.810537, -73.952317),
  (40.808032, -73.945816),
  (40.811627, -73.961497),
  (40.816135, -73.954403),
  (40.805321, -73.966098)],
 [(40.827654, -73.898451),
  (40.833677, -73.896573),
  (40.835184, -73.893692),
  (40.825224, -73.891469),
  (40.827371, -73.904648)],
 [(40.742029, -73.867697),
  (40.733131, -73.87111),
  (40.73691, -73.865842),
  (40.735753, -73.880849)],
 [(40.840077, -73.877143), (40.83609, -73.883724)],
 [],
 [(40.837051, -73.908246),
  (40.838419, -73.90142),
  (40.837071, -73.909064),
  (40.837051, -73.908246)],
 [(40.778101, -73.95178),
  (40.771608, -73.950711),
  (40.768021, -73.95627),
  (40.766086, -73.960501),
  (40.771608, -73.950711),
  (40.763493, -73.956358),
  (40.769589, -73.951606),
  (40.765961, -73.960592),
  (40.768021, -73.95627),
  (40.766086, -73.960501),
  (40.771595, -73.950665)],
 [],
 [],
 [(40.813059, -73.90877),
  (40.812135, -73.914305),
  (40.813636, -73.910427),
  (40.813636, -73.910427)],
 [(40.683101, -73.866056), (40.691426, -73.866977)],
 [(40.85487, -73.937071)],
 [(40.733818, -73.989734),
  (40.741317, -73.989891),
  (40.73908, -73.983136),
  (40.737902, -73.981214),
  (40.740017, -74.002919),
  (40.745548, -73.99886),
  (40.73301, -73.987564)],
 [(40.872479, -73.851401), (40.871056, -73.861527), (40.872831, -73.85182)],
 [],
 [(40.690543, -73.989365),
  (40.698276, -73.982605),
  (40.689355, -73.985244),
  (40.69595, -73.990913),
  (40.689723, -73.983149)],
 [(40.741317, -73.989891), (40.740017, -74.002919), (40.745548, -73.99886)],
 [],
 [(40.582038, -73.829007)],
 [(40.743654, -73.855795), (40.731336, -73.848904)],
 [(40.708184, -74.01258)],
 [(40.84406, -73.865572),
  (40.846021, -73.884755),
  (40.840077, -73.877143),
  (40.83609, -73.883724),
  (40.840676, -73.864393)],
 [(40.689355, -73.985244), (40.689723, -73.983149), (40.681641, -73.976815)],
 [(40.688998, -73.930369),
  (40.684141, -73.929003),
  (40.688871, -73.926901),
  (40.69027, -73.945377)],
 [(40.696653, -73.915132)],
 [],
 [(40.706872, -73.943041), (40.715978, -73.940148), (40.702976, -73.945783)],
 [],
 [(40.833677, -73.896573),
  (40.835184, -73.893692),
  (40.83609, -73.883724),
  (40.825224, -73.891469)],
 [(40.790869, -73.942429),
  (40.787422, -73.947546),
  (40.782671, -73.948406),
  (40.784504, -73.947414),
  (40.793388, -73.949529),
  (40.787422, -73.947546),
  (40.795858, -73.938818),
  (40.787168, -73.953762)],
 [],
 [(40.848087, -73.900912),
  (40.852055, -73.903581),
  (40.8558, -73.901267),
  (40.860263, -73.891171),
  (40.8558, -73.901267),
  (40.86251, -73.897871),
  (40.862464, -73.900526)],
 [(40.725168, -73.975629),
  (40.716474, -73.980305),
  (40.723087, -73.979467),
  (40.713462, -73.982304)],
 [(40.81041, -73.937101),
  (40.816469, -73.939329),
  (40.821187, -73.93605),
  (40.811462, -73.927591),
  (40.812823, -73.925757),
  (40.814448, -73.936259),
  (40.817602, -73.923121),
  (40.815011, -73.936132),
  (40.813812, -73.940424)],
 [(40.871993, -73.882629), (40.87956, -73.885606), (40.876716, -73.889717)],
 [(40.640487, -73.906077)],
 [(40.817193, -73.84745), (40.827698, -73.849723), (40.824712, -73.858864)],
 [(40.791345, -73.96878), (40.791017, -73.972419), (40.781084, -73.97627)],
 [(40.692842, -73.831814),
  (40.688246, -73.819201),
  (40.701705, -73.831562),
  (40.698176, -73.835156),
  (40.700017, -73.830529),
  (40.690527, -73.824257),
  (40.696271, -73.838195),
  (40.701705, -73.831562),
  (40.691894, -73.819462)],
 [(40.682848, -74.003843)],
 [],
 [(40.812874, -73.949044),
  (40.81384, -73.956494),
  (40.810537, -73.952317),
  (40.811627, -73.961497),
  (40.820098, -73.946484),
  (40.820098, -73.946484),
  (40.816135, -73.954403),
  (40.821104, -73.957165),
  (40.823131, -73.953102)],
 [(40.740017, -74.002919), (40.745548, -73.99886)]]

In [388]:
distances_all = {}
school = 1
for x,y in zip(lst1_grouped_1, lst2_grouped_2):
    
    distances = {}
    for i in x:
        distances[i] = []
        for j in y:
            distances[i].append(geopy.distance.geodesic(i, j).km)
    distances_all[school] = distances
    school+=1

In [213]:

from pulp import *

In [215]:
problem = LpProblem('Bus_Assignment',LpMinimize)

In [336]:
z_c = LpVariable('Z_c', lowBound=0 ,  cat=LpBinary)
y_pc = LpVariable('Y_pc', lowBound=0 , cat=LpBinary)
d_pc = [i[1] for i in distances_all[1]]

In [322]:
for i in lst2_grouped_2:
    print(i)

[(40.812874, -73.949044), (40.81384, -73.956494), (40.810537, -73.952317), (40.808032, -73.945816), (40.811627, -73.961497), (40.816135, -73.954403), (40.805321, -73.966098)]
[(40.827654, -73.898451), (40.833677, -73.896573), (40.835184, -73.893692), (40.825224, -73.891469), (40.827371, -73.904648)]
[(40.742029, -73.867697), (40.733131, -73.87111), (40.73691, -73.865842), (40.735753, -73.880849)]
[(40.840077, -73.877143), (40.83609, -73.883724)]
[]
[(40.837051, -73.908246), (40.838419, -73.90142), (40.837071, -73.909064), (40.837051, -73.908246)]
[(40.778101, -73.95178), (40.771608, -73.950711), (40.768021, -73.95627), (40.766086, -73.960501), (40.771608, -73.950711), (40.763493, -73.956358), (40.769589, -73.951606), (40.765961, -73.960592), (40.768021, -73.95627), (40.766086, -73.960501), (40.771595, -73.950665)]
[]
[]
[(40.813059, -73.90877), (40.812135, -73.914305), (40.813636, -73.910427), (40.813636, -73.910427)]
[(40.683101, -73.866056), (40.691426, -73.866977)]
[(40.85487, -73.937071)]
[(40.733818, -73.989734), (40.741317, -73.989891), (40.73908, -73.983136), (40.737902, -73.981214), (40.740017, -74.002919), (40.745548, -73.99886), (40.73301, -73.987564)]
[(40.872479, -73.851401), (40.871056, -73.861527), (40.872831, -73.85182)]
[]
[(40.690543, -73.989365), (40.698276, -73.982605), (40.689355, -73.985244), (40.69595, -73.990913), (40.689723, -73.983149)]
[(40.741317, -73.989891), (40.740017, -74.002919), (40.745548, -73.99886)]
[]
[(40.582038, -73.829007)]
[(40.743654, -73.855795), (40.731336, -73.848904)]
[(40.708184, -74.01258)]
[(40.84406, -73.865572), (40.846021, -73.884755), (40.840077, -73.877143), (40.83609, -73.883724), (40.840676, -73.864393)]
[(40.689355, -73.985244), (40.689723, -73.983149), (40.681641, -73.976815)]
[(40.688998, -73.930369), (40.684141, -73.929003), (40.688871, -73.926901), (40.69027, -73.945377)]
[(40.696653, -73.915132)]
[]
[(40.706872, -73.943041), (40.715978, -73.940148), (40.702976, -73.945783)]
[]
[(40.833677, -73.896573), (40.835184, -73.893692), (40.83609, -73.883724), (40.825224, -73.891469)]
[(40.790869, -73.942429), (40.787422, -73.947546), (40.782671, -73.948406), (40.784504, -73.947414), (40.793388, -73.949529), (40.787422, -73.947546), (40.795858, -73.938818), (40.787168, -73.953762)]
[]
[(40.848087, -73.900912), (40.852055, -73.903581), (40.8558, -73.901267), (40.860263, -73.891171), (40.8558, -73.901267), (40.86251, -73.897871), (40.862464, -73.900526)]
[(40.725168, -73.975629), (40.716474, -73.980305), (40.723087, -73.979467), (40.713462, -73.982304)]
[(40.81041, -73.937101), (40.816469, -73.939329), (40.821187, -73.93605), (40.811462, -73.927591), (40.812823, -73.925757), (40.814448, -73.936259), (40.817602, -73.923121), (40.815011, -73.936132), (40.813812, -73.940424)]
[(40.871993, -73.882629), (40.87956, -73.885606), (40.876716, -73.889717)]
[(40.640487, -73.906077)]
[(40.817193, -73.84745), (40.827698, -73.849723), (40.824712, -73.858864)]
[(40.791345, -73.96878), (40.791017, -73.972419), (40.781084, -73.97627)]
[(40.692842, -73.831814), (40.688246, -73.819201), (40.701705, -73.831562), (40.698176, -73.835156), (40.700017, -73.830529), (40.690527, -73.824257), (40.696271, -73.838195), (40.701705, -73.831562), (40.691894, -73.819462)]
[(40.682848, -74.003843)]
[]
[(40.812874, -73.949044), (40.81384, -73.956494), (40.810537, -73.952317), (40.811627, -73.961497), (40.820098, -73.946484), (40.820098, -73.946484), (40.816135, -73.954403), (40.821104, -73.957165), (40.823131, -73.953102)]
[(40.740017, -74.002919), (40.745548, -73.99886)]

In [325]:
from scipy.optimize import linprog

In [ ]:
obj = [lpSum(z_c),lpSum() ]

In [366]:
f=LpAffineExpression(LpElement('x'))
f

1*x + 0

In [418]:
# c: all of the stops for the school
items = list(range(len(lst2_grouped_2[0])))
people = list(range(len(lst1_grouped_1[0])))

In [430]:
def solverloop():
    n1 = 0
    n2 = 0
    while n1!= len(lst2_grouped_2):
        for i in list(range(len(lst2_grouped_2[n1]))):
            for j in list(range(len(lst1_grouped_1[0]))):
                problem = pulp.LpProblem("Bus Stop Assignment", pulp.LpMinimize)

# Define the decision variables
                z = {c: pulp.LpVariable(f"z_{c}", cat="Binary") for c in items}
                y = {(p, c): pulp.LpVariable(f"y_{p}_{c}", cat="Binary") for p in people for c in items}

# Define the objective function
                problem += pulp.lpSum([z[c] + d.get((p, c), 0) * y[(p, c)] for p in people for c in items])


# Define the constraints
                for p in people:
                    problem += pulp.lpSum([y[p, c] for p in people for c in items]) == 1

                for c in items:
                    for p in people:
                        problem += y[p, c] <= z[c]

                problem += pulp.lpSum([z[c] for c in items]) == 3

# Solve the problem
                status = problem.solve()

# Print the solution
                if status == pulp.LpStatusOptimal:
                    print("Optimal solution found")
                for c in items:
                    if z[c].value() == 1:
                        print(f"Item {c} is selected")
                else:
                    print("No optimal solution found")

In [431]:
solverloop()

In [424]:
import pulp

# Define the problem
problem = pulp.LpProblem("Bus Stop Assignment", pulp.LpMinimize)

# Define the decision variables
z = {c: pulp.LpVariable(f"z_{c}", cat="Binary") for c in items}
y = {(p, c): pulp.LpVariable(f"y_{p}_{c}", cat="Binary") for p in people for c in items}

# Define the objective function
problem += pulp.lpSum([z[c] + d.get((p, c), 0) * y[(p, c)] for p in people for c in items])


# Define the constraints
for p in people:
    problem += pulp.lpSum([y[p, c] for p in people for c in items]) == 1

for c in items:
    for p in people:
        problem += y[p, c] <= z[c]

problem += pulp.lpSum([z[c] for c in items]) == 3

# Solve the problem
status = problem.solve()

# Print the solution
if status == pulp.LpStatusOptimal:
    print("Optimal solution found")
    for c in items:
        if z[c].value() == 1:
            print(f"Item {c} is selected")
else:
    print("No optimal solution found")

Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /opt/homebrew/lib/python3.11/site-packages/pulp/solverdir/cbc/osx/64/cbc /var/folders/ym/tr9p7y314096r29j5qvndy4c0000gn/T/2bb28da6751247448d9dd651448a6cd7-pulp.mps timeMode elapsed branch printingOptions all solution /var/folders/ym/tr9p7y314096r29j5qvndy4c0000gn/T/2bb28da6751247448d9dd651448a6cd7-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 54 COLUMNS
At line 503 RHS
At line 553 BOUNDS
At line 603 ENDATA
Problem MODEL has 49 rows, 49 columns and 343 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 18 - 0.00 seconds
Cgl0003I 0 fixed, 0 tightened bounds, 36 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 42 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 42 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 39 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 14 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 2 tightened bounds, 7 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 7 tightened bounds, 7 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 7 tightened bounds, 7 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 7 tightened bounds, 7 strengthened rows, 0 substitutions
Cgl0004I processed model has 21 rows, 26 columns (26 integer (26 of which binary)) and 93 elements
Cutoff increment increased from 1e-05 to 5.9999
Cbc0038I Initial state - 0 integers unsatisfied sum - 0
Cbc0038I Solution found of 18
Cbc0038I Before mini branch and bound, 26 integers at bound fixed and 0 continuous
Cbc0038I Mini branch and bound did not improve solution (0.02 seconds)
Cbc0038I After 0.02 seconds - Feasibility pump exiting with objective of 18 - took 0.00 seconds
Cbc0012I Integer solution of 18 found by feasibility pump after 0 iterations and 0 nodes (0.02 seconds)
Cbc0001I Search completed - best objective 18, took 0 iterations and 0 nodes (0.02 seconds)
Cbc0035I Maximum depth 0, 0 variables fixed on reduced cost
Cuts at root node changed objective from 18 to 18
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                18.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.01
Time (Wallclock seconds):       0.02

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.01   (Wallclock seconds):       0.03

Optimal solution found
Item 0 is selected
Item 2 is selected
Item 4 is selected

In [425]:
for c in items:
    if pulp.value(z[c]) == 1:
        print(f"Item {c} is selected")
        for p in people:
            if pulp.value(y[(p, c)]) == 1:
                print(f" - Person {p} is assigned to item {c}")

Item 0 is selected
Item 2 is selected
 - Person 3 is assigned to item 2
Item 4 is selected

In [426]:

# Solve the problem
problem.solve()

# Check the status of the solution
print("Status:", pulp.LpStatus[problem.status])

# Print the optimal objective value
print("Optimal objective value:", pulp.value(problem.objective))

Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /opt/homebrew/lib/python3.11/site-packages/pulp/solverdir/cbc/osx/64/cbc /var/folders/ym/tr9p7y314096r29j5qvndy4c0000gn/T/895553d6905b413dbc96bc4dca46c538-pulp.mps timeMode elapsed branch printingOptions all solution /var/folders/ym/tr9p7y314096r29j5qvndy4c0000gn/T/895553d6905b413dbc96bc4dca46c538-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 54 COLUMNS
At line 503 RHS
At line 553 BOUNDS
At line 603 ENDATA
Problem MODEL has 49 rows, 49 columns and 343 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 18 - 0.00 seconds
Cgl0003I 0 fixed, 0 tightened bounds, 36 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 42 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 42 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 39 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 0 tightened bounds, 14 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 2 tightened bounds, 7 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 7 tightened bounds, 7 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 7 tightened bounds, 7 strengthened rows, 0 substitutions
Cgl0003I 0 fixed, 7 tightened bounds, 7 strengthened rows, 0 substitutions
Cgl0004I processed model has 21 rows, 26 columns (26 integer (26 of which binary)) and 93 elements
Cutoff increment increased from 1e-05 to 5.9999
Cbc0038I Initial state - 0 integers unsatisfied sum - 0
Cbc0038I Solution found of 18
Cbc0038I Before mini branch and bound, 26 integers at bound fixed and 0 continuous
Cbc0038I Mini branch and bound did not improve solution (0.01 seconds)
Cbc0038I After 0.01 seconds - Feasibility pump exiting with objective of 18 - took 0.00 seconds
Cbc0012I Integer solution of 18 found by feasibility pump after 0 iterations and 0 nodes (0.01 seconds)
Cbc0001I Search completed - best objective 18, took 0 iterations and 0 nodes (0.01 seconds)
Cbc0035I Maximum depth 0, 0 variables fixed on reduced cost
Cuts at root node changed objective from 18 to 18
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                18.00000000
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.01
Time (Wallclock seconds):       0.01

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.01   (Wallclock seconds):       0.01

Status: Optimal
Optimal objective value: 18.0

In [427]:
for var in problem.variables():
    if var.varValue == 1.0:
        print(var.name, var.varValue)

y_3_2 1.0
z_0 1.0
z_2 1.0
z_4 1.0